"use strict";

const Academic=require("./studAcademicModel.class.js");
const Domain=require("./studHumanisationModel.class.js");

function camel(row){if(!row)return null;const out={};Object.entries(row).forEach(([key,value])=>out[key.replace(/_([a-z])/g,(_m,c)=>c.toUpperCase())]=value);return out;}
function parse(row){if(!row)return null;const value=camel(row);["preferencesJson","preferredPhrasesJson","avoidedPhrasesJson","fingerprintJson","goalsJson","protectedSpansJson","editorialCategoriesJson","sourceValuesJson","candidateValuesJson"].forEach(key=>{if(Object.hasOwn(value,key)){value[key.replace(/Json$/,"")]=Domain.parseJson(value[key],key.includes("preferences")||key.includes("fingerprint")?{}:[]);delete value[key];}});return Object.freeze(value);}

class StudHumanisationRepository{
    constructor(store){if(!store)throw new Error("StudAcademicStore is required.");this.store=store;store.initialize();this.db=store.db;}
    transaction(work){return this.store.transaction(work);}
    profileRow(id){const row=parse(this.db.prepare("SELECT * FROM stud_humanisation_profiles WHERE id=?").get(Academic.safeId(id,"Profile ID")));if(!row)throw new Academic.StudError("NOT_FOUND","Humanisation Profile does not exist.");return row;}
    revisionRow(id){const row=parse(this.db.prepare("SELECT * FROM stud_humanisation_profile_revisions WHERE id=?").get(Academic.safeId(id,"Profile Revision ID")));if(!row)throw new Academic.StudError("NOT_FOUND","Humanisation Profile revision does not exist.");return row;}
    sampleRow(id){const row=parse(this.db.prepare("SELECT * FROM stud_humanisation_writing_samples WHERE id=?").get(Academic.safeId(id,"Writing Sample ID")));if(!row)throw new Academic.StudError("NOT_FOUND","Writing Sample does not exist.");return row;}
    sessionRow(id){const row=parse(this.db.prepare("SELECT * FROM stud_humanisation_sessions WHERE id=?").get(Academic.safeId(id,"Humanisation Session ID")));if(!row)throw new Academic.StudError("NOT_FOUND","Humanisation Session does not exist.");return row;}
    insertProfile(value){const id=Academic.createId("humanisation_profile"),revisionId=Academic.createId("humanisation_profile_revision"),now=Academic.now();this.db.prepare("INSERT INTO stud_humanisation_profiles (id,name,genre,lifecycle,current_revision_id,row_version,created_at,updated_at) VALUES (?,?,?,'ACTIVE',NULL,1,?,?)").run(id,value.name,value.genre,now,now);this.db.prepare(`INSERT INTO stud_humanisation_profile_revisions (id,profile_id,revision,origin,preferences_json,preferred_phrases_json,avoided_phrases_json,custom_notes,fingerprint_json,profile_hash,created_at) VALUES (?,?,1,?,?,?,?,?,?,?,?)`).run(revisionId,id,value.origin,JSON.stringify(value.preferences),JSON.stringify(value.preferredPhrases),JSON.stringify(value.avoidedPhrases),value.customNotes,JSON.stringify(value.fingerprint),value.profileHash,now);this.db.prepare("UPDATE stud_humanisation_profiles SET current_revision_id=? WHERE id=?").run(revisionId,id);return this.hydrateProfile(id);}
    insertProfileRevision(profile,value,origin){const latest=this.db.prepare("SELECT MAX(revision) value FROM stud_humanisation_profile_revisions WHERE profile_id=?").get(profile.id),revision=Number(latest.value||0)+1,id=Academic.createId("humanisation_profile_revision"),now=Academic.now();this.db.prepare(`INSERT INTO stud_humanisation_profile_revisions (id,profile_id,revision,origin,preferences_json,preferred_phrases_json,avoided_phrases_json,custom_notes,fingerprint_json,profile_hash,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).run(id,profile.id,revision,origin,JSON.stringify(value.preferences),JSON.stringify(value.preferredPhrases),JSON.stringify(value.avoidedPhrases),value.customNotes,JSON.stringify(value.fingerprint),value.profileHash,now);const updated=this.db.prepare("UPDATE stud_humanisation_profiles SET name=?,genre=?,current_revision_id=?,row_version=row_version+1,updated_at=? WHERE id=? AND row_version=?").run(value.name, value.genre,id,now,profile.id,profile.rowVersion);if(!updated.changes)throw new Academic.StudError("STALE_HUMANISATION_PROFILE","Profile changed before this revision was saved.");return this.hydrateProfile(profile.id);}
    hydrateProfile(id,options={}){const profile=this.profileRow(id),revision=this.revisionRow(profile.currentRevisionId),limit=Math.max(1,Math.min(Number(options.historyLimit)||20,Domain.LIMITS.profileHistory)),history=Object.freeze(this.db.prepare("SELECT * FROM stud_humanisation_profile_revisions WHERE profile_id=? ORDER BY revision DESC LIMIT ?").all(profile.id,limit).map(parse)),samples=Object.freeze(this.db.prepare("SELECT * FROM stud_humanisation_writing_samples WHERE profile_id=? AND state='ACTIVE' ORDER BY updated_at DESC,id DESC LIMIT ?").all(profile.id,Domain.LIMITS.samples).map(parse));return Object.freeze({...profile,currentRevision:revision,history,samples});}
    listProfiles(options={}){const limit=Math.max(1,Math.min(Number(options.limit)||50,100)),rows=this.db.prepare(`SELECT id FROM stud_humanisation_profiles ${options.includeArchived?"":"WHERE lifecycle='ACTIVE'"} ORDER BY updated_at DESC,id DESC LIMIT ?`).all(limit);return Object.freeze(rows.map(row=>this.hydrateProfile(row.id,{historyLimit:5})));}
    updateLifecycle(profile, lifecycle){const now=Academic.now(),result=this.db.prepare("UPDATE stud_humanisation_profiles SET lifecycle=?,row_version=row_version+1,updated_at=? WHERE id=? AND row_version=?").run(lifecycle,now,profile.id,profile.rowVersion);if(!result.changes)throw new Academic.StudError("STALE_HUMANISATION_PROFILE","Profile changed before it was archived.");return this.hydrateProfile(profile.id);}
    insertSample(value){const id=Academic.createId("humanisation_sample"),now=Academic.now();this.db.prepare(`INSERT INTO stud_humanisation_writing_samples (id,profile_id,source_type,canonical_object_type,canonical_object_id,authorship,genre,label,text_snapshot,content_hash,state,row_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,'ACTIVE',1,?,?)`).run(id,value.profileId,value.sourceType,value.canonicalObjectType,value.canonicalObjectId,value.authorship,value.genre,value.label,value.textSnapshot,value.contentHash,now,now);return this.sampleRow(id);}
    removeSample(sample,expectedVersion){const now=Academic.now(),result=this.db.prepare("UPDATE stud_humanisation_writing_samples SET state='REMOVED',row_version=row_version+1,updated_at=? WHERE id=? AND row_version=? AND state='ACTIVE'").run(now,sample.id,expectedVersion);if(!result.changes)throw new Academic.StudError("STALE_HUMANISATION_SAMPLE","Writing Sample changed before removal.");return this.sampleRow(sample.id);}
    insertSession(value,sections){const id=Academic.createId("humanisation_session"),now=Academic.now();this.db.prepare(`INSERT INTO stud_humanisation_sessions (id,assignment_id,draft_id,source_draft_version_id,source_content_hash,composition_plan_id,composition_plan_revision,composition_plan_hash,requirements_contract_id,requirements_contract_revision,requirements_contract_hash,profile_id,profile_revision_id,profile_hash,scope,goals_json,editorial_note,state,runtime,model,capability_state,run_id,candidate_hash,integrity_state,decision,resulting_draft_version_id,error_summary,row_version,created_at,updated_at,finished_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'CREATED',NULL,NULL,NULL,NULL,NULL,'PENDING',NULL,NULL,NULL,1,?,?,NULL)`).run(id,value.assignmentId,value.draftId,value.sourceDraftVersionId,value.sourceContentHash,value.compositionPlanId,value.compositionPlanRevision,value.compositionPlanHash,value.requirementsContractId,value.requirementsContractRevision,value.requirementsContractHash,value.profileId,value.profileRevisionId,value.profileHash,value.scope,JSON.stringify(value.goals),value.editorialNote,now,now);const statement=this.db.prepare(`INSERT INTO stud_humanisation_session_sections (id,session_id,section_id,section_order,source_content_hash,protected_spans_json,candidate_content,candidate_content_hash,integrity_state,editorial_categories_json,decision,created_at,updated_at) VALUES (?,?,?,?,?,?,NULL,NULL,'PENDING','[]','PENDING',?,?)`);sections.forEach(item=>statement.run(Academic.createId("humanisation_section"),id,item.sectionId,item.sectionOrder,item.sourceContentHash,JSON.stringify(item.protectedSpans),now,now));return this.hydrateSession(id);}
    sessionSections(id){return Object.freeze(this.db.prepare("SELECT * FROM stud_humanisation_session_sections WHERE session_id=? ORDER BY section_order,id").all(id).map(parse));}
    checks(id){return Object.freeze(this.db.prepare("SELECT * FROM stud_humanisation_integrity_checks WHERE session_id=? ORDER BY section_id,check_type,id").all(id).map(parse));}
    hydrateSession(id){const session=this.sessionRow(id);return Object.freeze({...session,sections:this.sessionSections(session.id),integrityChecks:this.checks(session.id)});}
    listSessions(input={}){const limit=Math.max(1,Math.min(Number(input.limit)||20,Domain.LIMITS.sessions));return Object.freeze(this.db.prepare("SELECT id FROM stud_humanisation_sessions WHERE assignment_id=? AND (? IS NULL OR draft_id=?) ORDER BY updated_at DESC,id DESC LIMIT ?").all(input.assignmentId,input.draftId||null,input.draftId||null,limit).map(row=>this.hydrateSession(row.id)));}
    startSession(session,value){const now=Academic.now(),result=this.db.prepare("UPDATE stud_humanisation_sessions SET state='RUNNING',runtime=?,model=?,capability_state=?,run_id=?,row_version=row_version+1,updated_at=? WHERE id=? AND row_version=? AND state='CREATED'").run(value.runtime,value.model,value.capabilityState,value.runId||null,now,session.id,session.rowVersion);if(!result.changes)throw new Academic.StudError("STALE_HUMANISATION_SESSION","Session changed before the operation started.");return this.hydrateSession(session.id);}
    saveCandidate(session,sections,checks,state,candidateHash,integrityState,runtimeResult={}){const now=Academic.now();this.db.prepare("DELETE FROM stud_humanisation_integrity_checks WHERE session_id=?").run(session.id);const sectionStatement=this.db.prepare("UPDATE stud_humanisation_session_sections SET candidate_content=?,candidate_content_hash=?,integrity_state=?,editorial_categories_json=?,updated_at=? WHERE session_id=? AND section_id=?");sections.forEach(item=>sectionStatement.run(item.candidateContent,item.candidateContentHash,item.integrityState,JSON.stringify(item.editorialCategories),now,session.id,item.sectionId));const checkStatement=this.db.prepare(`INSERT INTO stud_humanisation_integrity_checks (id,session_id,section_id,check_type,state,source_values_json,candidate_values_json,summary,created_at) VALUES (?,?,?,?,?,?,?,?,?)`);checks.forEach(item=>checkStatement.run(Academic.createId("humanisation_check"),session.id,item.sectionId||null,item.type,item.state,JSON.stringify(item.sourceValues||[]),JSON.stringify(item.candidateValues||[]),item.summary,now));const result=this.db.prepare("UPDATE stud_humanisation_sessions SET state=?,candidate_hash=?,integrity_state=?,model=?,capability_state=?,row_version=row_version+1,updated_at=? WHERE id=? AND row_version=? AND state='RUNNING'").run(state,candidateHash,integrityState,runtimeResult.model||null,runtimeResult.capabilityState||null,now,session.id,session.rowVersion);if(!result.changes)throw new Academic.StudError("STALE_HUMANISATION_SESSION","Session changed before its candidate was stored.");return this.hydrateSession(session.id);}
    failSession(session,state,errorSummary){const now=Academic.now(),result=this.db.prepare("UPDATE stud_humanisation_sessions SET state=?,error_summary=?,row_version=row_version+1,updated_at=?,finished_at=? WHERE id=? AND row_version=? AND state IN ('CREATED','RUNNING')").run(state,errorSummary||null,now,now,session.id,session.rowVersion);if(!result.changes)throw new Academic.StudError("STALE_HUMANISATION_SESSION","Session changed before it could be closed.");return this.hydrateSession(session.id);}
    decide(session,value){const now=Academic.now(),result=this.db.prepare("UPDATE stud_humanisation_sessions SET state=?,decision=?,resulting_draft_version_id=?,row_version=row_version+1,updated_at=?,finished_at=? WHERE id=? AND row_version=? AND state IN ('CANDIDATE_READY','NEEDS_REVIEW')").run(value.state,value.decision,value.resultingDraftVersionId||null,now,now,session.id,session.rowVersion);if(!result.changes)throw new Academic.StudError("STALE_HUMANISATION_SESSION","Session changed before the decision was saved.");if(value.sectionDecisions){const statement=this.db.prepare("UPDATE stud_humanisation_session_sections SET decision=?,updated_at=? WHERE session_id=? AND section_id=?");value.sectionDecisions.forEach(item=>statement.run(item.decision,now,session.id,item.sectionId));}return this.hydrateSession(session.id);}
}

module.exports=Object.freeze({StudHumanisationRepository,camel,parse});
