"use strict";

class StudFacultyScoutWorkspace {
    constructor(options={}){this.request=options.request;this.escape=options.escape||(value=>String(value||""));this.showToast=options.showToast||(()=>{});this.parent=options.parent;this.state={data:null,loading:false,error:"",selectedFacultyId:""};}
    reset(){this.state={data:null,loading:false,error:"",selectedFacultyId:""};}
    assignment(){return this.parent.assignment();}
    plan(){return this.parent.researchPlan.plan();}
    topic(){return this.parent.researchPlan.selectedTopic();}
    selectedFaculty(){const values=this.state.data&&this.state.data.identities||[];return values.find(item=>item.id===this.state.selectedFacultyId)||values[0]||null;}
    async refresh(){const assignment=this.assignment(),topic=this.topic();if(!assignment)return;this.state.loading=true;this.state.error="";try{this.state.data=await this.request("stud-faculty-scout-state",{assignmentId:assignment.id,topicId:topic&&topic.id||undefined,limit:50});if(!this.state.selectedFacultyId&&this.state.data.identities[0])this.state.selectedFacultyId=this.state.data.identities[0].id;}catch(error){this.state.error=error.message||"FACULTY SCOUT UNAVAILABLE";}finally{this.state.loading=false;}}
    async open(){await this.parent.researchPlan.open();await this.refresh();}
    role(value){return String(value||"UNKNOWN").replace(/_/g," ");}
    status(identity){if(identity.resolutionState==="CONFIRMED")return "CONFIRMED BY USER";if((identity.candidates||[]).length)return "CANDIDATES NEED REVIEW";return "IDENTITY NOT RESOLVED";}
    renderIdentityList(){const identities=this.state.data&&this.state.data.identities||[];return `<aside class="stud-faculty-identities"><header><small>OBSERVED TEACHING TEAM</small><span>${identities.length}</span></header>${identities.length?`<ol>${identities.map(item=>`<li><button type="button" data-stud-faculty-select="${this.escape(item.id)}" class="${this.selectedFaculty()&&this.selectedFaculty().id===item.id?"is-current":""}"><strong>${this.escape(item.displayName)}</strong><span>${this.escape(item.institution||"Institution not recorded")}</span><small>${this.escape(this.status(item))}</small></button></li>`).join("")}</ol>`:`<p>No faculty observation has been recorded for this Assignment.</p>`}<details><summary>ADD FACULTY OBSERVATION</summary><form data-stud-faculty-create><label>NAME<input name="displayName" required maxlength="300" autocomplete="off"></label><label>ROLE<select name="role"><option>COURSE_LECTURER</option><option>MODULE_LEADER</option><option>ASSIGNMENT_AUTHOR</option><option>SUPERVISOR</option><option>TUTOR</option><option>TEACHING_TEAM</option><option>OTHER</option><option selected>UNKNOWN</option></select></label><label>INSTITUTION<input name="institution" maxlength="500"></label><label>DEPARTMENT<input name="department" maxlength="500"></label><label>ORCID (OPTIONAL)<input name="orcid" maxlength="40" placeholder="0000-0000-0000-0000"></label><label>SOURCE<select name="sourceType"><option value="USER">USER OBSERVATION</option><option value="COURSE_METADATA">COURSE CONTEXT</option><option value="ASSIGNMENT_METADATA">ASSIGNMENT CONTEXT</option></select></label><button type="submit">RECORD OBSERVATION</button></form></details></aside>`;}
    renderCandidates(identity){if(!identity)return `<section class="stud-faculty-panel"><h3>Select an observed person</h3><p>Public scholarly identity discovery is always explicit.</p></section>`;const candidates=identity.candidates||[];return `<section class="stud-faculty-panel"><header><div><small>IDENTITY RESOLUTION</small><h3>${this.escape(identity.displayName)}</h3><p>${this.escape(this.role(identity.observations&&identity.observations[0]&&identity.observations[0].role))} · ${this.escape(identity.institution||"institution unknown")}</p></div><button type="button" data-stud-faculty-discover="${this.escape(identity.id)}"${identity.resolutionState==="CONFIRMED"?" disabled":""}>FIND PUBLIC SCHOLARLY RECORDS</button></header>${identity.resolutionState==="CONFIRMED"?`<div class="stud-faculty-confirmed"><strong>IDENTITY CONFIRMED BY USER</strong><span>OpenAlex ${this.escape(identity.confirmedProviderAuthorId||"")}${identity.confirmedOrcid?` · ORCID ${this.escape(identity.confirmedOrcid)}`:""}</span><p>Confirmation identifies the public author record. It does not establish quality or relevance for this Assignment.</p></div>`:""}${candidates.length?`<ol class="stud-faculty-candidates">${candidates.map(candidate=>`<li class="is-${candidate.disposition.toLowerCase()}"><div><strong>${this.escape(candidate.displayName)}</strong><span>${this.escape((candidate.institutions||[]).join(" · ")||"No public affiliation supplied")}</span><small>${this.escape(candidate.assessment)} · ${candidate.worksCount} works${candidate.orcid?` · ORCID ${this.escape(candidate.orcid)}`:""}</small><p>${this.escape((candidate.reasons||[]).join(" · "))}</p></div>${candidate.disposition==="PENDING"?`<nav><button type="button" data-stud-faculty-confirm="${this.escape(candidate.id)}" data-faculty-id="${this.escape(identity.id)}" data-faculty-version="${identity.rowVersion}">CONFIRM MATCH</button><button type="button" data-stud-faculty-reject="${this.escape(candidate.id)}" data-faculty-id="${this.escape(identity.id)}" data-candidate-version="${candidate.rowVersion}">NOT THIS PERSON</button></nav>`:`<em>${this.escape(candidate.disposition)}</em>`}</li>`).join("")}</ol>`:`<p class="stud-faculty-empty">No public identity candidates loaded. Search occurs only when requested and may return no result.</p>`}</section>`;}
    renderPublications(identity){const plan=this.plan(),topic=this.topic(),items=this.state.data&&this.state.data.publications||[];if(!plan||!topic)return `<section class="stud-faculty-publications"><h3>SELECT A RESEARCH TOPIC</h3><p>Faculty publications are assessed only against an explicit Topic context.</p></section>`;return `<section class="stud-faculty-publications"><header><div><small>PUBLICATIONS FOR THIS TOPIC</small><h3>${this.escape(topic.title)}</h3><p>Author identity and Topic relevance are separate gates. A Faculty Gem is a relevant publication by a user-confirmed faculty identity—not an authority badge.</p></div><button type="button" data-stud-faculty-publications="${this.escape(identity&&identity.id||"")}"${!identity||identity.resolutionState!=="CONFIRMED"?" disabled":""}>DISCOVER PUBLICATIONS</button></header>${items.length?`<ol>${items.map(item=>`<li class="is-${item.relevanceState.toLowerCase()}"><div><small>${this.escape(item.relevanceState)}${item.disposition==="IMPORTED"?" · IN DOSSIER":""}</small><strong>${this.escape(item.title)}</strong><span>${this.escape((item.authors||[]).map(author=>author.displayName).join(", "))}${item.publicationYear?` · ${item.publicationYear}`:""}</span><p>${this.escape((item.reasons||[]).join(" · "))}</p>${(item.matchedTerms||[]).length?`<em>MATCHED: ${this.escape(item.matchedTerms.join(" · "))}</em>`:""}</div><nav>${item.disposition==="SUGGESTED"&&item.relevanceState==="RELEVANT"?`<button type="button" data-stud-faculty-import="${this.escape(item.id)}" data-publication-version="${item.rowVersion}">ADD TO TOPIC DOSSIER</button>`:""}${item.disposition==="SUGGESTED"?`<button type="button" data-stud-faculty-dismiss="${this.escape(item.id)}" data-publication-version="${item.rowVersion}">DISMISS</button>`:""}</nav></li>`).join("")}</ol>`:`<p class="stud-faculty-empty">No publication candidates loaded for this Topic. Nothing is searched automatically.</p>`}<footer>Dossier membership is not Evidence. M8 support, contradiction and citation integrity require separate explicit review.</footer></section>`;}
    render(){if(this.state.loading&&!this.state.data)return `<section class="stud-faculty-scout"><p>LOADING LOCAL FACULTY CONTEXT…</p></section>`;if(this.state.error)return `<section class="stud-faculty-scout is-error"><strong>FACULTY SCOUT UNAVAILABLE</strong><p>${this.escape(this.state.error)}</p><button type="button" data-stud-faculty-refresh>RETRY</button></section>`;const identity=this.selectedFaculty();return `<section class="stud-faculty-scout"><header><div><small>FACULTY LITERATURE SCOUT</small><h2>Teaching context → confirmed identity → relevant publications</h2><p>Public scholarly discovery is explicit, bounded and explainable. No profile crawling, AI matching or automatic Evidence creation.</p></div><button type="button" data-stud-faculty-refresh>REFRESH LOCAL STATE</button></header><div class="stud-faculty-layout">${this.renderIdentityList()}<main>${this.renderCandidates(identity)}${this.renderPublications(identity)}</main></div></section>`;}
    async handleClick(event){const refresh=event.target.closest("[data-stud-faculty-refresh]"),select=event.target.closest("[data-stud-faculty-select]"),discover=event.target.closest("[data-stud-faculty-discover]"),confirm=event.target.closest("[data-stud-faculty-confirm]"),reject=event.target.closest("[data-stud-faculty-reject]"),publications=event.target.closest("[data-stud-faculty-publications]"),importButton=event.target.closest("[data-stud-faculty-import]"),dismiss=event.target.closest("[data-stud-faculty-dismiss]");if(!refresh&&!select&&!discover&&!confirm&&!reject&&!publications&&!importButton&&!dismiss)return false;try{const assignment=this.assignment(),plan=this.plan(),topic=this.topic();if(select){this.state.selectedFacultyId=select.dataset.studFacultySelect;this.parent.parent.render();return true;}if(discover)await this.request("stud-faculty-identity-discover",{assignmentId:assignment.id,facultyId:discover.dataset.studFacultyDiscover,requestId:`faculty-${Date.now()}`,limit:10});else if(confirm)await this.request("stud-faculty-identity-confirm",{assignmentId:assignment.id,facultyId:confirm.dataset.facultyId,candidateId:confirm.dataset.studFacultyConfirm,expectedVersion:Number(confirm.dataset.facultyVersion)});else if(reject)await this.request("stud-faculty-identity-reject",{assignmentId:assignment.id,facultyId:reject.dataset.facultyId,candidateId:reject.dataset.studFacultyReject,expectedVersion:Number(reject.dataset.candidateVersion)});else if(publications)await this.request("stud-faculty-publications-discover",{assignmentId:assignment.id,planId:plan.id,topicId:topic.id,facultyId:publications.dataset.studFacultyPublications,requestId:`faculty-works-${Date.now()}`,limit:25});else if(importButton)await this.request("stud-faculty-publication-import",{assignmentId:assignment.id,publicationId:importButton.dataset.studFacultyImport,expectedVersion:Number(importButton.dataset.publicationVersion)});else if(dismiss)await this.request("stud-faculty-publication-dismiss",{assignmentId:assignment.id,publicationId:dismiss.dataset.studFacultyDismiss,expectedVersion:Number(dismiss.dataset.publicationVersion)});await this.refresh();this.parent.parent.render();}catch(error){this.showToast(this.parent.parent.view,error.message||"FACULTY SCOUT ACTION UNAVAILABLE");}return true;}
    async handleSubmit(event){const form=event.target.closest("[data-stud-faculty-create]");if(!form)return false;event.preventDefault();try{const data=new FormData(form);await this.request("stud-faculty-observation-create",{assignmentId:this.assignment().id,displayName:data.get("displayName"),institution:data.get("institution")||undefined,department:data.get("department")||undefined,orcid:data.get("orcid")||undefined,role:data.get("role"),sourceType:data.get("sourceType")});await this.refresh();this.parent.parent.render();}catch(error){this.showToast(this.parent.parent.view,error.message||"FACULTY OBSERVATION UNAVAILABLE");}return true;}
}

if(typeof window!=="undefined")window.StudFacultyScoutWorkspace=StudFacultyScoutWorkspace;
if(typeof module!=="undefined")module.exports={StudFacultyScoutWorkspace};
