"use strict";

// The renderer is an editor and viewer only. It never evaluates notebook
// source, reads arbitrary paths or performs network requests directly.
class StudNotebookWorkspace {
    constructor(options = {}) {
        this.request = options.request;
        this.escape = options.escape || (value => String(value || ""));
        this.showToast = options.showToast || (() => {});
        this.parent = options.parent || null;
        this.state = {tab: "NOTEBOOKS", capabilities: null, notebooks: [], datasets: [], repositories: [], selectedNotebook: null, selectedDataset: null, selectedRepository: null, datasetAnalysis: null, error: null};
    }

    async initialize() { await this.refresh(); }
    async refresh() {
        const [capabilities, notebooks, datasets, repositories] = await Promise.all([
            this.request("stud-notebook-capabilities"), this.request("stud-notebook-list", {limit: 100}), this.request("stud-dataset-list", {limit: 100}), this.request("stud-github-list", {limit: 100})
        ]);
        this.state.capabilities = capabilities; this.state.notebooks = notebooks; this.state.datasets = datasets; this.state.repositories = repositories;
        if (this.state.selectedNotebook && !notebooks.some(item => item.id === this.state.selectedNotebook.notebook.id)) this.state.selectedNotebook = null;
        if (this.state.selectedDataset && !datasets.some(item => item.id === this.state.selectedDataset.dataset.id)) this.state.selectedDataset = null;
        if (this.state.selectedRepository && !repositories.some(item => item.id === this.state.selectedRepository.id)) this.state.selectedRepository = null;
    }

    render() {
        const caps = this.state.capabilities || {}; const status = caps.notebook && caps.notebook.execution || "CHECKING";
        return `<section class="stud-notebook-shell" aria-label="Notebook, Data and GitHub academic workbench">
            <header class="stud-notebook-intro workspace-panel"><div><small>STUD / LOCAL ACADEMIC WORKBENCH</small><h2>NOTEBOOK / DATA / GITHUB</h2><p>Structured local notebooks, managed tabular data and explicit public repository references. No shell, arbitrary interpreter, hidden save or background request.</p></div><div class="stud-notebook-status"><small>NOTEBOOK ENGINE</small><strong>${this.escape(status)}</strong><span>EDIT / INSPECT / EXPLICIT</span></div></header>
            <nav class="stud-notebook-tabs" aria-label="Academic workbench sections">${["NOTEBOOKS", "DATA", "GITHUB"].map(tab => `<button type="button" data-stud-notebook-tab="${tab}" class="${this.state.tab === tab ? "active" : ""}">${tab}</button>`).join("")}</nav>
            ${this.state.error ? `<section class="workspace-panel stud-empty-state"><div class="workspace-panel-content"><strong>WORKBENCH ERROR</strong><p>${this.escape(this.state.error)}</p></div></section>` : this.state.tab === "NOTEBOOKS" ? this.renderNotebooks() : this.state.tab === "DATA" ? this.renderData() : this.renderGitHub()}
            <section class="workspace-panel stud-notebook-policy"><header><h2>WORKBENCH POLICY</h2><span>LOCAL / BOUNDED / FAIL-CLOSED</span></header><div class="workspace-panel-content"><p>Notebook execution is intentionally unavailable in this release. CSV/TSV imports are explicit and copied to managed STUD storage without retaining the original path. GitHub uses only an explicit public metadata request to a fixed endpoint; no token, clone, file import or polling is available.</p></div></section>
        </section>`;
    }

    courseOptions() { return (this.parent.state.courses || []).map(course => `<option value="${this.escape(course.id)}">${this.escape(course.code || course.shortName || course.title)}</option>`).join(""); }
    assignmentOptions() { return (this.parent.state.assignments || []).map(item => `<option value="${this.escape(item.id)}">${this.escape(item.title)}</option>`).join(""); }
    contextFields(selected = {}) { return `<label>COURSE<select class="aegis-select" name="courseId"><option value="">NO COURSE</option>${this.courseOptions()}</select></label><label>ASSIGNMENT<select class="aegis-select" name="assignmentId"><option value="">NO ASSIGNMENT</option>${this.assignmentOptions()}</select></label>`; }

    renderNotebooks() {
        const context = this.state.selectedNotebook; const notebook = context && context.notebook;
        return `<section class="stud-notebook-grid"><article class="workspace-panel"><header><h2>NOTEBOOKS</h2><span>${this.state.notebooks.length} LOCAL</span></header><div class="workspace-panel-content"><form data-stud-notebook-form="create-notebook" class="stud-notebook-form"><label>TITLE<input class="aegis-input" name="title" maxlength="240" required placeholder="Assignment analysis notebook"></label><label>TYPE<select class="aegis-select" name="notebookType"><option>GENERAL</option><option>COMPUTATIONAL</option><option>DATA_ANALYSIS</option><option>CODE_EXERCISE</option><option>REPRODUCIBLE_APPENDIX</option><option>TEXT_ANALYSIS</option></select></label><label>LANGUAGE<select class="aegis-select" name="language"><option>TEXT</option><option>PYTHON</option><option>JAVASCRIPT</option><option>R</option><option>SQL</option><option>PSEUDOCODE</option></select></label>${this.contextFields()}<label>DESCRIPTION<textarea class="aegis-input" name="description" maxlength="12000" placeholder="Explicit local academic context"></textarea></label><button type="submit">CREATE NOTEBOOK</button></form><div class="stud-notebook-list">${this.state.notebooks.length ? this.state.notebooks.map(item => `<button type="button" data-stud-notebook-open="${this.escape(item.id)}" class="${notebook && notebook.id === item.id ? "selected" : ""}"><strong>${this.escape(item.title)}</strong><span>${this.escape(item.notebookType)} · ${this.escape(item.language)}</span><small>${this.escape(item.executionStatus)}</small></button>`).join("") : `<div class="stud-empty-inline">NO NOTEBOOKS YET · CREATION IS EXPLICIT AND LOCAL.</div>`}</div></div></article>
        <article class="workspace-panel stud-notebook-editor"><header><h2>${notebook ? this.escape(notebook.title) : "NOTEBOOK EDITOR"}</h2><span>${notebook ? this.escape(notebook.executionStatus) : "SELECT NOTEBOOK"}</span></header><div class="workspace-panel-content">${context ? this.renderNotebookEditor(context) : `<div class="stud-empty-inline">SELECT A NOTEBOOK. MARKDOWN IS RENDERED AS SAFE LOCAL TEXT; CODE IS STORED BUT NEVER EXECUTED.</div>`}</div></article></section>`;
    }

    renderNotebookEditor(context) {
        const notebook = context.notebook; const cells = context.cells || [];
        return `<section class="stud-notebook-detail"><form data-stud-notebook-form="update-notebook" data-notebook-id="${this.escape(notebook.id)}" class="stud-notebook-form"><label>TITLE<input class="aegis-input" name="title" maxlength="240" value="${this.escape(notebook.title)}"></label><label>DESCRIPTION<textarea class="aegis-input" name="description" maxlength="12000">${this.escape(notebook.description || "")}</textarea></label><button type="submit">SAVE NOTEBOOK</button><button type="button" data-stud-notebook-context="${this.escape(notebook.id)}">OPEN ACADEMIC CONTEXT</button></form><div class="stud-notebook-execution"><strong>EXECUTION · ${this.escape(context.execution.status)}</strong><span>${this.escape(context.execution.detail)}</span></div><form data-stud-notebook-form="add-cell" data-notebook-id="${this.escape(notebook.id)}" class="stud-notebook-add"><label>NEW CELL<select class="aegis-select" name="cellType"><option>MARKDOWN</option><option>CODE</option><option>RAW</option></select></label><button type="submit">ADD CELL</button></form><div class="stud-notebook-cells">${cells.length ? cells.map((cell, index) => this.renderCell(notebook, cell, index, cells.length)).join("") : `<div class="stud-empty-inline">NO CELLS · ADD MARKDOWN, CODE OR RAW ACADEMIC MATERIAL.</div>`}</div></section>`;
    }

    renderCell(notebook, cell, index, total) {
        const outputs = cell.outputs || [];
        return `<article class="stud-notebook-cell"><header><strong>${cell.cellType} CELL ${index + 1}</strong><span>${cell.executionState || "NOT_EXECUTED"}</span></header><form data-stud-notebook-form="save-cell" data-notebook-id="${this.escape(notebook.id)}" data-cell-id="${this.escape(cell.id)}"><label>CONTENT<textarea class="aegis-input" name="source" maxlength="20000">${this.escape(cell.source || "")}</textarea></label><input type="hidden" name="cellType" value="${this.escape(cell.cellType)}"><div class="stud-notebook-cell-actions"><button type="submit">SAVE CELL</button><button type="button" data-stud-notebook-move="UP" data-notebook-id="${this.escape(notebook.id)}" data-cell-id="${this.escape(cell.id)}" ${index === 0 ? "disabled" : ""}>MOVE UP</button><button type="button" data-stud-notebook-move="DOWN" data-notebook-id="${this.escape(notebook.id)}" data-cell-id="${this.escape(cell.id)}" ${index === total - 1 ? "disabled" : ""}>MOVE DOWN</button><button type="button" data-stud-notebook-duplicate="${this.escape(cell.id)}" data-notebook-id="${this.escape(notebook.id)}">DUPLICATE</button><button type="button" data-stud-notebook-delete="${this.escape(cell.id)}" data-notebook-id="${this.escape(notebook.id)}">DELETE</button></div></form>${cell.cellType === "MARKDOWN" ? `<section class="stud-notebook-markdown"><small>SAFE MARKDOWN SOURCE PREVIEW</small><pre>${this.escape(cell.source || "")}</pre></section>` : ""}${cell.cellType === "CODE" ? `<small class="stud-notebook-code-policy">CODE IS PERSISTED AS TEXT ONLY · EXECUTION NOT INSTALLED</small>` : ""}<section class="stud-notebook-outputs"><small>OUTPUTS · ${outputs.length}</small>${outputs.length ? `${outputs.map(output => `<pre>${this.escape(output.textContent || "MANAGED ARTIFACT")}</pre>`).join("")}<button type="button" data-stud-notebook-clear-output="${this.escape(cell.id)}" data-notebook-id="${this.escape(notebook.id)}">CLEAR OUTPUTS</button>` : `<span>NO OUTPUTS · NO EXECUTION ENGINE IS BUNDLED</span>`}</section></article>`;
    }

    renderData() {
        const selected = this.state.selectedDataset; const data = selected && selected.dataset; const analysis = this.state.datasetAnalysis;
        return `<section class="stud-notebook-grid"><article class="workspace-panel"><header><h2>MANAGED DATASETS</h2><span>${this.state.datasets.length} LOCAL</span></header><div class="workspace-panel-content"><form data-stud-notebook-form="import-dataset" class="stud-notebook-form"><label>TITLE <small>optional, selected file name by default</small><input class="aegis-input" name="title" maxlength="240"></label>${this.contextFields()}<label>DESCRIPTION<textarea class="aegis-input" name="description" maxlength="12000"></textarea></label><button type="submit">SELECT CSV / TSV</button><small>EXPLICIT PICKER · 8 MB · 20,000 ROWS · ORIGINAL PATH NOT PERSISTED</small></form><div class="stud-notebook-list">${this.state.datasets.length ? this.state.datasets.map(item => `<button type="button" data-stud-dataset-open="${this.escape(item.id)}" class="${data && data.id === item.id ? "selected" : ""}"><strong>${this.escape(item.title)}</strong><span>${this.escape(item.format)} · ${item.rowCount} ROWS</span><small>${this.escape(item.checksum || "")}</small></button>`).join("") : `<div class="stud-empty-inline">NO MANAGED DATASET YET.</div>`}</div></div></article><article class="workspace-panel stud-notebook-data-detail"><header><h2>${data ? this.escape(data.title) : "DATASET PREVIEW"}</h2><span>${data ? `${data.rowCount} ROWS` : "SELECT DATASET"}</span></header><div class="workspace-panel-content">${selected ? this.renderDatasetDetail(selected, analysis) : `<div class="stud-empty-inline">SELECT OR IMPORT ONE CSV/TSV FILE. NO DIRECTORY SCAN OR AUTOMATIC INGESTION EXISTS.</div>`}</div></article></section>`;
    }

    renderDatasetDetail(selected, analysis) {
        const columns = selected.columns || []; const preview = selected.preview || [];
        const header = columns.map(item => `<th>${this.escape(item.name)}</th>`).join("");
        return `<section class="stud-dataset-detail"><div class="stud-dataset-summary"><strong>${selected.summary.rows} ROWS · ${selected.summary.columns} COLUMNS</strong><span>${selected.summary.missingValues} MISSING VALUES</span></div><div class="stud-dataset-table"><table><thead><tr>${header}</tr></thead><tbody>${preview.slice(0, 20).map(row => `<tr>${row.map(value => `<td>${this.escape(value)}</td>`).join("")}</tr>`).join("")}</tbody></table></div><div class="stud-dataset-columns">${columns.map(column => `<article><strong>${this.escape(column.name)}</strong><span>${this.escape(column.type)}</span><small>${column.type === "NUMBER" ? `MIN ${column.minimum} · MAX ${column.maximum} · MEAN ${column.mean}` : `${column.distinct} DISTINCT`}</small></article>`).join("")}</div><form data-stud-notebook-form="analyze-dataset" data-dataset-id="${this.escape(selected.dataset.id)}" class="stud-notebook-form"><label>OPERATION<select class="aegis-select" name="operation"><option>SUMMARY</option><option>FREQUENCIES</option><option>PLOT</option></select></label><label>COLUMN<select class="aegis-select" name="column"><option value="">SELECT COLUMN</option>${columns.map(column => `<option>${this.escape(column.name)}</option>`).join("")}</select></label><label>PLOT TYPE<select class="aegis-select" name="plotType"><option>HISTOGRAM</option><option>BAR</option><option>LINE</option><option>SCATTER</option></select></label><label>Y COLUMN <small>line/scatter only</small><select class="aegis-select" name="yColumn"><option value="">SELECT Y</option>${columns.map(column => `<option>${this.escape(column.name)}</option>`).join("")}</select></label><label>TITLE<input class="aegis-input" name="title" maxlength="160" value="${this.escape(selected.dataset.title)}"></label><button type="submit">ANALYZE LOCALLY</button></form>${analysis ? this.renderDatasetAnalysis(analysis) : ""}<button type="button" data-stud-dataset-context="${this.escape(selected.dataset.id)}">OPEN ACADEMIC CONTEXT</button></section>`;
    }

    renderDatasetAnalysis(analysis) {
        if (!analysis.result || !analysis.result.plot) return `<section class="stud-dataset-analysis"><small>${this.escape(analysis.operation)}</small><pre>${this.escape(JSON.stringify(analysis.result, null, 2))}</pre></section>`;
        const plot = analysis.result.plot; const points = plot.points || []; const maximum = Math.max(1, ...points.map(point => Number(point.y) || 0));
        return `<section class="stud-dataset-analysis"><header><strong>${this.escape(plot.title)}</strong><span>${this.escape(plot.type)}</span></header><div class="stud-dataset-plot" role="img" aria-label="${this.escape(plot.title)}">${points.slice(0, 24).map(point => `<span title="${this.escape(`${point.x}: ${point.y}`)}" style="height:${Math.max(4, Math.round((Number(point.y) || 0) / maximum * 100))}%"><i>${this.escape(String(point.x))}</i></span>`).join("")}</div><small>${this.escape(plot.xLabel)} → ${this.escape(plot.yLabel)} · local deterministic analysis · not automatically persisted</small></section>`;
    }

    renderGitHub() {
        const selected = this.state.selectedRepository;
        return `<section class="stud-notebook-grid"><article class="workspace-panel"><header><h2>PUBLIC REPOSITORY REFERENCES</h2><span>${this.state.repositories.length} EXPLICIT</span></header><div class="workspace-panel-content"><form data-stud-notebook-form="create-repository" class="stud-notebook-form"><label>PUBLIC GITHUB REPOSITORY<input class="aegis-input" name="repository" maxlength="240" required placeholder="owner/repository"></label><label>REF <small>optional</small><input class="aegis-input" name="selectedRef" maxlength="160" placeholder="main"></label>${this.contextFields()}<button type="submit">SAVE REFERENCE</button><small>NO TOKEN · NO CLONE · NO FILE IMPORT · NO BACKGROUND CHECK</small></form><div class="stud-notebook-list">${this.state.repositories.length ? this.state.repositories.map(item => `<button type="button" data-stud-repository-open="${this.escape(item.id)}" class="${selected && selected.id === item.id ? "selected" : ""}"><strong>${this.escape(item.title)}</strong><span>${this.escape(item.selectedRef || "NO REF")}</span><small>${item.metadataJson ? "METADATA SAVED EXPLICITLY" : "REFERENCE ONLY"}</small></button>`).join("") : `<div class="stud-empty-inline">NO REPOSITORY REFERENCE YET.</div>`}</div></div></article><article class="workspace-panel"><header><h2>REPOSITORY CONTEXT</h2><span>${selected ? "PUBLIC / READ ONLY" : "SELECT REFERENCE"}</span></header><div class="workspace-panel-content">${selected ? this.renderRepositoryDetail(selected) : `<div class="stud-empty-inline">SAVE A PUBLIC owner/repository REFERENCE. METADATA IS NEVER REQUESTED UNTIL CHECK PUBLIC METADATA IS PRESSED.</div>`}</div></article></section>`;
    }

    renderRepositoryDetail(reference) {
        let metadata = {}; try { metadata = reference.metadataJson ? JSON.parse(reference.metadataJson) : {}; } catch (error) {}
        return `<section class="stud-repository-detail"><strong>${this.escape(reference.canonicalUrl)}</strong><p>${this.escape(metadata.description || "No public metadata has been checked yet.")}</p><dl><dt>DEFAULT REF</dt><dd>${this.escape(reference.selectedRef || metadata.defaultBranch || "UNKNOWN")}</dd><dt>LICENSE</dt><dd>${this.escape(metadata.license || "UNKNOWN")}</dd><dt>UPDATED</dt><dd>${this.escape(metadata.updatedAt || "NOT CHECKED")}</dd><dt>VISIBILITY</dt><dd>${this.escape(metadata.visibility || "REFERENCE ONLY")}</dd></dl><button type="button" data-stud-repository-metadata="${this.escape(reference.id)}">CHECK PUBLIC METADATA</button><button type="button" data-stud-repository-context="${this.escape(reference.id)}">OPEN ACADEMIC CONTEXT</button><small>Fixed GitHub public metadata endpoint only. The request is explicit, cancellable and has no token, custom headers or arbitrary URL field.</small></section>`;
    }

    async selectNotebook(id) { this.state.selectedNotebook = await this.request("stud-notebook-read", {notebookId: id}); this.state.datasetAnalysis = null; this.parent.render(); }
    async selectDataset(id) { this.state.selectedDataset = await this.request("stud-dataset-read", {datasetId: id}); this.state.datasetAnalysis = null; this.parent.render(); }
    async selectRepository(id) { this.state.selectedRepository = this.state.repositories.find(item => item.id === id) || null; this.parent.render(); }
    openContext(type, id) { this.parent.knowledge.state.rootType = type; this.parent.knowledge.state.rootId = id; this.parent.setActiveView("KNOWLEDGE"); this.parent.knowledge.build().catch(error => { this.parent.knowledge.state.error = error.message || "ACADEMIC CONTEXT FAILED"; this.parent.render(); }); }

    async handleClick(event) {
        const tab = event.target.closest("[data-stud-notebook-tab]"); if (tab) { this.state.tab = tab.dataset.studNotebookTab; this.parent.render(); return true; }
        const notebook = event.target.closest("[data-stud-notebook-open]"); if (notebook) { await this.selectNotebook(notebook.dataset.studNotebookOpen); return true; }
        const dataset = event.target.closest("[data-stud-dataset-open]"); if (dataset) { await this.selectDataset(dataset.dataset.studDatasetOpen); return true; }
        const repository = event.target.closest("[data-stud-repository-open]"); if (repository) { await this.selectRepository(repository.dataset.studRepositoryOpen); return true; }
        const context = event.target.closest("[data-stud-notebook-context], [data-stud-dataset-context], [data-stud-repository-context]"); if (context) { const type = context.dataset.studNotebookContext ? "NOTEBOOK" : context.dataset.studDatasetContext ? "DATASET" : "REPOSITORY_REFERENCE"; this.openContext(type, context.dataset.studNotebookContext || context.dataset.studDatasetContext || context.dataset.studRepositoryContext); return true; }
        const move = event.target.closest("[data-stud-notebook-move]"); if (move) { const cells = this.state.selectedNotebook.cells.map(cell => cell.id); const index = cells.indexOf(move.dataset.studNotebookCell); const next = move.dataset.studNotebookMove === "UP" ? index - 1 : index + 1; [cells[index], cells[next]] = [cells[next], cells[index]]; await this.request("stud-notebook-cell-reorder", {notebookId: move.dataset.studNotebookId, cellIds: cells}); await this.selectNotebook(move.dataset.studNotebookId); return true; }
        const duplicate = event.target.closest("[data-stud-notebook-duplicate]"); if (duplicate) { const cell = this.state.selectedNotebook.cells.find(item => item.id === duplicate.dataset.studNotebookDuplicate); await this.request("stud-notebook-cell-create", {notebookId: duplicate.dataset.studNotebookId, cellType: cell.cellType, source: cell.source, afterCellId: cell.id}); await this.selectNotebook(duplicate.dataset.studNotebookId); return true; }
        const remove = event.target.closest("[data-stud-notebook-delete]"); if (remove) { if (!window.confirm("Delete this notebook cell? This action cannot be undone.")) return true; await this.request("stud-notebook-cell-delete", {notebookId: remove.dataset.studNotebookId, cellId: remove.dataset.studNotebookDelete, confirmation: true}); await this.selectNotebook(remove.dataset.studNotebookId); return true; }
        const clear = event.target.closest("[data-stud-notebook-clear-output]"); if (clear) { if (!window.confirm("Clear the stored output for this cell?")) return true; await this.request("stud-notebook-output-clear", {notebookId: clear.dataset.notebookId, cellId: clear.dataset.studNotebookClearOutput, confirmation: true}); await this.selectNotebook(clear.dataset.notebookId); return true; }
        const metadata = event.target.closest("[data-stud-repository-metadata]"); if (metadata) { const requestId = `github_${Date.now()}`; const updated = await this.request("stud-github-metadata", {repositoryId: metadata.dataset.studRepositoryMetadata, requestId}); await this.refresh(); this.state.selectedRepository = updated; this.parent.render(); return true; }
        return false;
    }

    async handleSubmit(event) {
        const form = event.target.closest("form[data-stud-notebook-form]"); if (!form) return false; event.preventDefault(); const value = Object.fromEntries(new FormData(form).entries()); const kind = form.dataset.studNotebookForm;
        try {
            if (kind === "create-notebook") { const created = await this.request("stud-notebook-create", value); await this.refresh(); this.state.selectedNotebook = await this.request("stud-notebook-read", {notebookId: created.id}); }
            else if (kind === "update-notebook") { await this.request("stud-notebook-update", {notebookId: form.dataset.notebookId, value}); await this.selectNotebook(form.dataset.notebookId); }
            else if (kind === "add-cell") { await this.request("stud-notebook-cell-create", {notebookId: form.dataset.notebookId, cellType: value.cellType, source: ""}); await this.selectNotebook(form.dataset.notebookId); }
            else if (kind === "save-cell") { await this.request("stud-notebook-cell-update", {notebookId: form.dataset.notebookId, cellId: form.dataset.cellId, cellType: value.cellType, source: value.source}); await this.selectNotebook(form.dataset.notebookId); }
            else if (kind === "import-dataset") { const saved = await this.request("stud-dataset-import", value); if (!saved.cancelled) { await this.refresh(); await this.selectDataset(saved.id); } }
            else if (kind === "analyze-dataset") { this.state.datasetAnalysis = await this.request("stud-dataset-analyze", {datasetId: form.dataset.datasetId, operation: value.operation, input: value}); this.parent.render(); }
            else if (kind === "create-repository") { const saved = await this.request("stud-github-create", value); await this.refresh(); this.state.selectedRepository = saved; }
            this.state.error = null; this.parent.render();
        } catch (error) { this.state.error = error.message || "WORKBENCH OPERATION FAILED"; this.parent.render(); }
        return true;
    }
}

window.StudNotebookWorkspace = StudNotebookWorkspace;
