"use strict";

class StudCompositionWorkspace {
    constructor(options = {}) {
        this.request=options.request;this.escape=options.escape||(value=>String(value||""));this.showToast=options.showToast||(()=>{});this.parent=options.parent;
        this.reset();
    }
    reset(){this.state={data:null,requirements:null,evidenceMap:null,selectedSectionId:null,sectionContext:null,selectedDraftId:null,draft:null,viewedVersion:null,diff:null,busy:false,error:""};}
    assignment(){return this.parent.assignment();}
    plan(){return this.state.data&&(this.state.data.draft||this.state.data.current)||null;}
    selectedSection(){const p=this.plan();return p&&p.sections.find(item=>item.id===this.state.selectedSectionId)||p&&p.sections[0]||null;}
    async open(){const assignment=this.assignment();if(!assignment)return;this.state.busy=true;this.state.error="";this.state.viewedVersion=null;try{const [data,requirements,evidenceMap]=await Promise.all([this.request("stud-composition-state",{assignmentId:assignment.id,draftLimit:25}),this.request("stud-requirements-state",{assignmentId:assignment.id}),this.request("stud-evidence-map",{assignmentId:assignment.id,claimLimit:100,evidenceLimit:500})]);this.state.data=data;this.state.requirements=requirements;this.state.evidenceMap=evidenceMap;const p=this.plan();const context=this.parent.state.workingContext||{};this.state.selectedSectionId=p&&p.sections.some(item=>item.id===context.activeCompositionSection?.id)?context.activeCompositionSection.id:p&&p.sections[0]?.id||null;this.state.selectedDraftId=data.drafts.some(item=>item.id===context.activeDraftDocument?.id)?context.activeDraftDocument.id:data.drafts[0]?.id||null;if(this.state.selectedDraftId)this.state.draft=await this.request("stud-draft-read",{assignmentId:assignment.id,draftId:this.state.selectedDraftId,versionLimit:50});await this.loadSectionContext();}catch(error){this.state.error=error.message||"Composition workspace unavailable.";}finally{this.state.busy=false;this.parent.parent.render();}}
    async reload(message){await this.open();if(message)this.showToast(this.parent.parent.view,message);}
    async loadSectionContext(){const assignment=this.assignment(),plan=this.plan(),section=this.selectedSection();this.state.sectionContext=null;if(assignment&&plan&&section)this.state.sectionContext=await this.request("stud-composition-section-context",{assignmentId:assignment.id,planId:plan.id,sectionId:section.id});}
    contextPayload(extra={}){const assignment=this.assignment(),course=this.parent.course(),workflow=this.parent.workflow(),researchPlan=this.parent.researchPlan.plan();const plan=this.plan(),section=this.selectedSection(),draft=this.state.draft,version=this.state.viewedVersion||draft&&draft.currentVersion;return {courseId:course&&course.id||undefined,assignmentId:assignment&&assignment.id||undefined,workflowId:workflow&&workflow.id||undefined,researchPlanId:researchPlan&&researchPlan.id||plan&&plan.researchPlanId||undefined,compositionPlanId:plan&&plan.id||undefined,compositionSectionId:section&&section.id||undefined,draftDocumentId:draft&&draft.id||undefined,draftVersionId:version&&version.id||undefined,originSurface:"COMPOSITION_WORKSPACE",userPinned:false,...extra};}
    async persistContext(extra={}){try{const value=await this.request("stud-working-context-update",this.contextPayload(extra));this.parent.state.workingContext=value;this.parent.parent.state.workingContext=value;}catch(error){this.showToast(this.parent.parent.view,error.message||"WORKING CONTEXT NOT UPDATED");}}
    field(form,name){return String(new FormData(form).get(name)||"");}
    number(form,name){const value=this.field(form,name);return value===""?null:Number(value);}
    requirementItems(){const contract=this.state.requirements&&(this.state.requirements.current||this.state.requirements.draft);return contract&&contract.items||[];}
    claims(){return this.state.evidenceMap&&this.state.evidenceMap.claims||[];}
    evidenceForClaims(section){const ids=new Set((section&&section.claims||[]).map(item=>item.claimId)),map=new Map();this.claims().filter(node=>ids.has(node.claim.id)).forEach(node=>node.links.filter(link=>link.lifecycle==="REVIEWED"&&link.relationshipType!=="NOT_ASSESSED").forEach(link=>map.set(link.evidence.id,link.evidence)));return [...map.values()];}
    renderEmpty(){const assignment=this.assignment(),contract=this.state.requirements&&this.state.requirements.current;if(!contract)return `<section class="stud-composition-empty"><small>COMPOSITION</small><h2>Review the Assignment requirements first</h2><p>A Composition Plan cannot claim structure or limits until a reviewed Requirements Contract exists. Manual Assignments use the same local review path.</p><button type="button" data-stud-workspace-mode="REQUIREMENTS">OPEN REQUIREMENTS</button></section>`;return `<section class="stud-composition-empty"><small>COMPOSITION PLAN</small><h2>Turn reviewed requirements into a writing plan</h2><p>Create an inspectable structure. Proposed sections remain Draft until you review them.</p><button type="button" data-stud-composition-create>CREATE COMPOSITION PLAN</button></section>`;}
    lengthText(plan){const ready=this.state.data&&this.state.data.readiness,length=ready&&ready.length;if(!length)return "NO LENGTH PLAN";if(length.target===null)return `${length.planned} ${length.unit} PLANNED · NO AUTHORITATIVE TOTAL`;const delta=length.delta===0?"BALANCED":length.delta>0?`${length.delta} OVER`:`${Math.abs(length.delta)} UNDER`;return `${length.planned} / ${length.target} ${length.unit} · ${delta} · ${length.totalSource.replace(/_/g," ")}`;}
    draftLengthText(version){if(!version)return "NO SAVED VERSION";return ["WORDS","ITEMS"].includes(version.lengthUnit)?`${version.totalLength} ${version.lengthUnit}`:`LENGTH NOT AUTOMATICALLY MEASURED · ${version.lengthUnit}`;}
    renderHeader(plan){const readiness=this.state.data.readiness||{state:"NEEDS_REVIEW",reasons:[]};return `<header class="stud-composition-heading"><div><small>COMPOSITION PLAN · REV ${plan.revision}</small><h2>${this.escape(plan.title)}</h2><p>${this.escape(this.lengthText(plan))}</p></div><div><span class="stud-composition-state">${this.escape(plan.lifecycle)}</span><span>${this.escape(readiness.state.replace(/_/g," "))}</span>${plan.lifecycle==="DRAFT"?`<button type="button" data-stud-composition-review data-version="${plan.rowVersion}">REVIEW PLAN</button>`:`<button type="button" data-stud-composition-revise data-version="${plan.rowVersion}">CREATE PLAN REVISION</button>`}${plan.lifecycle==="REVIEWED"?`<button type="button" data-stud-draft-create>CREATE DRAFT</button>`:""}</div></header>`;}
    renderPlanSettings(plan){if(plan.lifecycle!=="DRAFT")return "";return `<details class="stud-composition-plan-settings"><summary>PLAN SETTINGS</summary><form data-stud-composition-plan-update><label>TITLE<input name="title" maxlength="240" required value="${this.escape(plan.title)}"></label><div><label>LENGTH UNIT<select name="lengthUnit">${["WORDS","PAGES","SLIDES","MINUTES","ITEMS","OTHER"].map(unit=>`<option${unit===plan.lengthUnit?" selected":""}>${unit}</option>`).join("")}</select></label><label>USER PLANNED TOTAL<input name="userPlannedTotal" type="number" min="0" step="any" value="${plan.userPlannedTotal??""}"></label></div><p>${plan.authoritativeTotal===null?"No unambiguous authoritative total was found in the reviewed Contract.":`The reviewed Contract provides ${plan.authoritativeTotal} ${this.escape(plan.lengthUnit)}. A user plan does not overwrite it.`}</p><label>PLANNING NOTES<textarea name="userNotes" maxlength="12000" rows="2">${this.escape(plan.userNotes||"")}</textarea></label><button type="submit">SAVE PLAN SETTINGS</button></form></details>`;}
    renderSections(plan,selected){return `<aside class="stud-composition-outline"><header><small>DOCUMENT STRUCTURE</small><strong>${plan.sections.length} SECTIONS</strong></header><nav>${plan.sections.length?plan.sections.map(section=>`<button type="button" class="${selected&&selected.id===section.id?"is-current":""}" style="--stud-section-depth:${section.depth}" data-stud-composition-section="${this.escape(section.id)}"><span>${section.sectionOrder+1}</span><strong>${this.escape(section.title)}</strong><small>${section.plannedLength===null?"NO ALLOCATION":`${section.plannedLength} ${section.lengthUnit}`}</small></button>`).join(""):`<p>No Sections yet. Add the first reviewed-purpose unit.</p>`}</nav>${plan.lifecycle==="DRAFT"?`<details><summary>ADD SECTION</summary><form data-stud-composition-section-add><label>TITLE<input name="title" maxlength="240" required></label><label>PURPOSE<textarea name="purpose" maxlength="12000" rows="3" required></textarea></label><label>PARENT<select name="parentSectionId"><option value="">TOP LEVEL</option>${plan.sections.map(section=>`<option value="${this.escape(section.id)}">${this.escape(section.title)}</option>`).join("")}</select></label><div><label>ORDER<input name="order" type="number" min="0" value="${plan.sections.length}"></label><label>PLANNED LENGTH<input name="plannedLength" type="number" min="0" step="any"></label></div><label>UNIT<select name="lengthUnit">${["WORDS","PAGES","SLIDES","MINUTES","ITEMS","OTHER"].map(unit=>`<option${unit===plan.lengthUnit?" selected":""}>${unit}</option>`).join("")}</select></label><button type="submit">ADD SECTION</button></form></details>`:""}</aside>`;}
    currentContent(section){const version=this.state.viewedVersion||this.state.draft&&this.state.draft.currentVersion;const snapshot=version&&version.sections.find(item=>item.sectionId===section.id);return snapshot&&snapshot.content||"";}
    renderWriter(plan,section){if(!section)return `<main class="stud-composition-writer"><div class="stud-composition-empty-inline"><strong>PLAN STRUCTURE REQUIRED</strong><p>Add a Section with an explicit purpose before drafting.</p></div></main>`;const draft=this.state.draft,viewed=this.state.viewedVersion,content=this.currentContent(section),editable=Boolean(draft&&plan.lifecycle==="REVIEWED"&&!viewed),version=viewed||draft&&draft.currentVersion;return `<main class="stud-composition-writer"><header><div><small>CURRENT SECTION</small><h3>${this.escape(section.title)}</h3><p>${this.escape(section.purpose)}</p></div>${section.origin!=="USER"?`<span>${this.escape(section.origin.replace(/_/g," "))}</span>`:""}</header>${plan.lifecycle==="DRAFT"?this.renderSectionEditor(plan,section):""}${viewed?`<div class="stud-composition-version-banner"><span>READ-ONLY HISTORICAL VERSION ${viewed.versionNumber}</span><button type="button" data-stud-draft-current>RETURN TO CURRENT</button></div>`:""}${draft?`<form data-stud-draft-save><label class="stud-composition-writing-label">DRAFT TEXT<textarea name="content" rows="18" maxlength="120000" ${editable?"":"disabled"}>${this.escape(content)}</textarea></label><label>CHANGE REASON<input name="changeReason" maxlength="4000" placeholder="What changed in this version?" ${editable?"":"disabled"}></label><div><span>${version?`${viewed?"HISTORICAL":"CURRENT"} VERSION ${version.versionNumber} · ${this.escape(this.draftLengthText(version))}`:"NO SAVED VERSION"}</span><button type="submit" ${editable?"":"disabled"}>SAVE NEW VERSION</button></div></form>`:`<section class="stud-composition-no-draft"><strong>PLAN FIRST, DRAFT SECOND</strong><p>Review this plan before creating a Draft Document. Plan review does not complete Workflow work.</p></section>`}${draft&&draft.history.length?this.renderHistory(draft):""}</main>`;}
    renderSectionEditor(plan,section){return `<details class="stud-composition-section-editor"><summary>EDIT SECTION PLAN</summary><form data-stud-composition-section-update><input type="hidden" name="sectionVersion" value="${section.rowVersion}"><label>TITLE<input name="title" maxlength="240" required value="${this.escape(section.title)}"></label><label>PURPOSE<textarea name="purpose" maxlength="12000" rows="3" required>${this.escape(section.purpose)}</textarea></label><label>PARENT<select name="parentSectionId"><option value="">TOP LEVEL</option>${plan.sections.filter(item=>item.id!==section.id).map(item=>`<option value="${this.escape(item.id)}"${item.id===section.parentSectionId?" selected":""}>${this.escape(item.title)}</option>`).join("")}</select></label><div><label>ORDER<input name="order" type="number" min="0" value="${section.sectionOrder}"></label><label>PLANNED LENGTH<input name="plannedLength" type="number" min="0" step="any" value="${section.plannedLength??""}"></label></div><label>UNIT<select name="lengthUnit">${["WORDS","PAGES","SLIDES","MINUTES","ITEMS","OTHER"].map(unit=>`<option${unit===section.lengthUnit?" selected":""}>${unit}</option>`).join("")}</select></label><label>WHY THIS SECTION EXISTS<textarea name="originReason" maxlength="4000" rows="2" required>${this.escape(section.originReason)}</textarea></label><label>NOTES<textarea name="notes" maxlength="12000" rows="2">${this.escape(section.notes||"")}</textarea></label><div><button type="submit">SAVE SECTION</button><button type="button" data-stud-composition-section-remove data-version="${section.rowVersion}">REMOVE</button></div></form></details>`;}
    renderHistory(draft){const [latest,previous]=draft.history;return `<section class="stud-composition-history"><header><small>VERSION HISTORY</small>${previous?`<button type="button" data-stud-draft-diff data-from="${this.escape(previous.id)}" data-to="${this.escape(latest.id)}">COMPARE V${previous.versionNumber} → V${latest.versionNumber}</button>`:""}</header>${this.state.diff?this.renderDiff(this.state.diff):`<ol>${draft.history.slice(0,10).map(version=>`<li><button type="button" data-stud-draft-version="${this.escape(version.id)}"><strong>V${version.versionNumber}</strong><span>${this.escape(version.origin)} · ${version.totalLength} ${version.lengthUnit}</span><small>${this.escape(version.changeReason||"No change reason recorded")}</small></button></li>`).join("")}</ol>`}</section>`;}
    renderDiff(diff){return `<div class="stud-composition-diff"><header><strong>V${diff.from.version} → V${diff.to.version}</strong><span>${diff.changedSections} CHANGED SECTIONS · ${diff.lengthDelta>=0?"+":""}${diff.lengthDelta}</span></header>${diff.sections.filter(item=>item.changed).map(section=>`<details open><summary>${this.escape(section.title)} · ${section.lengthDelta>=0?"+":""}${section.lengthDelta}</summary><pre>${section.diff.lines.map(line=>`<span class="is-${line.type.toLowerCase()}">${line.type==="ADDED"?"+":line.type==="REMOVED"?"−":" "} ${this.escape(line.text)}</span>`).join("\n")}</pre></details>`).join("")}</div>`;}
    renderSupport(plan,section){
        if(!section)return `<aside class="stud-composition-support"><p>Select a Section to inspect its planning context.</p></aside>`;
        const requirements=section.requirements||[],claims=section.claims||[],evidence=this.evidenceForClaims(section),coverage=plan.requirementCoverage||[],coveredIds=new Set(coverage.map(item=>item.requirementItemId)),availableRequirements=this.requirementItems().filter(item=>!coveredIds.has(item.id)),excluded=coverage.filter(item=>item.disposition==="EXCLUDED");
        const requirementHtml=requirements.length?requirements.map(item=>`<article><strong>${this.escape(item.label)}</strong><small>${this.escape(item.displayValue||item.resolutionState)}</small>${plan.lifecycle==="DRAFT"?`<button type="button" data-stud-composition-unlink="REQUIREMENT" data-target="${item.requirementItemId}">REMOVE</button>`:""}</article>`).join(""):`<p>No Requirement is assigned. This does not prove the Section is invalid.</p>`;
        const assignHtml=plan.lifecycle==="DRAFT"&&availableRequirements.length?`<form data-stud-composition-requirement><select name="requirementItemId">${availableRequirements.map(item=>`<option value="${item.id}">${this.escape(item.label)}</option>`).join("")}</select><button type="submit">ASSIGN</button></form>`:"";
        const exclusionHtml=excluded.length?`<details><summary>${excluded.length} INTENTIONALLY EXCLUDED</summary>${excluded.map(item=>`<article><strong>${this.escape(item.label)}</strong><small>${this.escape(item.reason)}</small></article>`).join("")}</details>`:"";
        const excludeForm=plan.lifecycle==="DRAFT"&&availableRequirements.length?`<details><summary>EXCLUDE WITH REASON</summary><form data-stud-composition-requirement-exclude><select name="requirementItemId">${availableRequirements.map(item=>`<option value="${item.id}">${this.escape(item.label)}</option>`).join("")}</select><textarea name="reason" maxlength="4000" rows="2" required placeholder="Why this Requirement is intentionally outside this Composition Plan"></textarea><button type="submit">RECORD EXCLUSION</button></form></details>`:"";
        return `<aside class="stud-composition-support"><header><small>WHY / SUPPORT</small><strong>${this.escape(section.title)}</strong></header><section><h4>REQUIREMENTS</h4>${requirementHtml}${assignHtml}${exclusionHtml}${excludeForm}</section><section><h4>CLAIMS</h4>${claims.length?claims.map(claim=>`<article><strong>${this.escape(claim.claimText)}</strong><small>${this.escape(claim.lifecycle)} · ${this.escape(claim.claimType)}</small>${plan.lifecycle==="DRAFT"?`<button type="button" data-stud-composition-unlink="CLAIM" data-target="${claim.claimId}">REMOVE</button>`:""}</article>`).join(""):`<p>No Claims placed in this Section.</p>`}${plan.lifecycle==="DRAFT"?this.renderClaimLinkForm(section):""}</section><section><h4>EVIDENCE / CITATIONS</h4>${evidence.length?evidence.map(item=>this.renderEvidence(item,section,plan)).join(""):`<p>No explicitly assessed Evidence is available for the Claims in this Section.</p>`}</section><section class="stud-composition-readiness"><h4>READINESS REASONS</h4>${(this.state.data.readiness?.reasons||[]).slice(0,20).map(reason=>`<p><strong>${this.escape(reason.code.replace(/_/g," "))}</strong>${this.escape(reason.message)}</p>`).join("")||"<p>No structural readiness issue is currently recorded. This is not a quality judgement.</p>"}</section></aside>`;
    }
    renderClaimLinkForm(section){const available=this.claims().map(node=>node.claim).filter(claim=>!section.claims.some(item=>item.claimId===claim.id));return available.length?`<form data-stud-composition-claim><select name="claimId">${available.map(claim=>`<option value="${claim.id}">${this.escape(claim.claimText.slice(0,120))}</option>`).join("")}</select><button type="submit">PLACE CLAIM</button></form>`:"";}
    renderEvidence(item,section,plan){const link=(this.state.sectionContext?.claims||[]).flatMap(claim=>claim.links||[]).find(value=>value.evidence&&value.evidence.id===item.id),integrity=link&&link.evidence&&link.evidence.citationIntegrity,freshness=link&&link.evidence&&link.evidence.freshness;return `<article><strong>${this.escape(item.excerpt||`${item.sourceObjectType} evidence`)}</strong><small>${this.escape(freshness?.state||item.reviewState)} · ${this.escape(integrity?.state||"CITATION UNKNOWN")}</small><div>${integrity&&integrity.state==="READY"?`<button type="button" data-stud-composition-citation="${item.id}">INSERT ${this.escape(integrity.rendered.style.toUpperCase())} CITATION</button>`:""}${plan.lifecycle==="DRAFT"&&!section.evidence.some(value=>value.evidenceId===item.id)?`<button type="button" data-stud-composition-evidence="${item.id}">PLAN EVIDENCE USE</button>`:""}<button type="button" data-stud-workspace-mode="EVIDENCE_MAP">INSPECT SOURCE</button></div></article>`;}
    render(){if(this.state.busy)return `<section class="stud-composition-loading">LOADING LOCAL COMPOSITION STATE…</section>`;if(this.state.error)return `<section class="stud-composition-empty is-error"><strong>COMPOSITION UNAVAILABLE</strong><p>${this.escape(this.state.error)}</p><button type="button" data-stud-composition-reload>RETRY</button></section>`;const plan=this.plan();if(!plan)return this.renderEmpty();const section=this.selectedSection();return `<section class="stud-composition-workspace">${this.renderHeader(plan)}${this.renderPlanSettings(plan)}<div class="stud-composition-layout">${this.renderSections(plan,section)}${this.renderWriter(plan,section)}${this.renderSupport(plan,section)}</div></section>`;}
    async handleClick(event){
        const find=selector=>event.target.closest(selector),create=find("[data-stud-composition-create]"),reload=find("[data-stud-composition-reload]"),select=find("[data-stud-composition-section]"),review=find("[data-stud-composition-review]"),revise=find("[data-stud-composition-revise]"),remove=find("[data-stud-composition-section-remove]"),unlink=find("[data-stud-composition-unlink]"),evidence=find("[data-stud-composition-evidence]"),draftCreate=find("[data-stud-draft-create]"),diff=find("[data-stud-draft-diff]"),citation=find("[data-stud-composition-citation]"),version=find("[data-stud-draft-version]"),current=find("[data-stud-draft-current]");
        if(!create&&!reload&&!select&&!review&&!revise&&!remove&&!unlink&&!evidence&&!draftCreate&&!diff&&!citation&&!version&&!current)return false;
        try{
            const assignment=this.assignment(),plan=this.plan(),section=this.selectedSection();
            if(create)await this.request("stud-composition-create",{assignmentId:assignment.id,contractId:this.state.requirements.current.id,researchPlanId:this.parent.researchPlan.plan()?.id,workflowId:this.parent.workflow()?.id,seedProposals:true});
            else if(reload)return this.open(),true;
            else if(select){this.state.selectedSectionId=select.dataset.studCompositionSection;this.state.diff=null;await this.loadSectionContext();await this.persistContext();this.parent.parent.render();return true;}
            else if(review)await this.request("stud-composition-review",{planId:plan.id,expectedVersion:Number(review.dataset.version)});
            else if(revise)await this.request("stud-composition-create-revision",{planId:plan.id,expectedVersion:Number(revise.dataset.version)});
            else if(remove)await this.request("stud-composition-section-remove",{planId:plan.id,sectionId:section.id,expectedPlanVersion:plan.rowVersion,expectedSectionVersion:Number(remove.dataset.version)});
            else if(unlink)await this.request("stud-composition-reference-unlink",{planId:plan.id,expectedVersion:plan.rowVersion,sectionId:section.id,kind:unlink.dataset.studCompositionUnlink,targetId:unlink.dataset.target});
            else if(evidence)await this.request("stud-composition-evidence-link",{planId:plan.id,expectedVersion:plan.rowVersion,sectionId:section.id,evidenceId:evidence.dataset.studCompositionEvidence,intendedUse:"Explicitly planned for this Section."});
            else if(draftCreate)await this.request("stud-draft-create",{assignmentId:assignment.id,planId:plan.id,title:`${plan.title} draft`});
            else if(diff){this.state.diff=await this.request("stud-draft-diff",{assignmentId:assignment.id,draftId:this.state.draft.id,fromVersionId:diff.dataset.from,toVersionId:diff.dataset.to});this.parent.parent.render();return true;}
            else if(version){this.state.viewedVersion=await this.request("stud-draft-version-read",{assignmentId:assignment.id,draftId:this.state.draft.id,versionId:version.dataset.studDraftVersion});this.state.diff=null;await this.persistContext({draftVersionId:this.state.viewedVersion.id});this.parent.parent.render();return true;}
            else if(current){this.state.viewedVersion=null;this.state.diff=null;await this.persistContext();this.parent.parent.render();return true;}
            else if(citation){const id=citation.dataset.studCompositionCitation,link=(this.state.sectionContext?.claims||[]).flatMap(claim=>claim.links||[]).find(value=>value.evidence&&value.evidence.id===id),text=link?.evidence?.citationIntegrity?.rendered?.citation;if(text){const area=this.parent.parent.view.querySelector("[data-stud-draft-save] textarea[name='content']");if(area&&!area.disabled){area.value=`${area.value}${area.value&&!area.value.endsWith(" ")?" ":""}${text}`;area.focus();}}return true;}
            await this.reload("COMPOSITION UPDATED");
        }catch(error){this.showToast(this.parent.parent.view,error.message||"COMPOSITION ACTION FAILED");}
        return true;
    }
    async handleSubmit(event){
        const form=event.target.closest("form");if(!form)return false;const plan=this.plan(),section=this.selectedSection(),assignment=this.assignment();
        try{
            if(form.matches("[data-stud-composition-plan-update]")){event.preventDefault();await this.request("stud-composition-update",{planId:plan.id,expectedVersion:plan.rowVersion,title:this.field(form,"title"),lengthUnit:this.field(form,"lengthUnit"),userPlannedTotal:this.number(form,"userPlannedTotal"),userNotes:this.field(form,"userNotes")});}
            else if(form.matches("[data-stud-composition-section-add]")){event.preventDefault();await this.request("stud-composition-section-add",{planId:plan.id,expectedVersion:plan.rowVersion,section:{title:this.field(form,"title"),purpose:this.field(form,"purpose"),parentSectionId:this.field(form,"parentSectionId")||null,order:this.number(form,"order"),plannedLength:this.number(form,"plannedLength"),lengthUnit:this.field(form,"lengthUnit"),originReason:"User-defined composition structure."}});}
            else if(form.matches("[data-stud-composition-section-update]")){event.preventDefault();await this.request("stud-composition-section-update",{planId:plan.id,sectionId:section.id,expectedPlanVersion:plan.rowVersion,expectedSectionVersion:Number(this.field(form,"sectionVersion")),section:{title:this.field(form,"title"),purpose:this.field(form,"purpose"),parentSectionId:this.field(form,"parentSectionId")||null,order:this.number(form,"order"),plannedLength:this.number(form,"plannedLength"),lengthUnit:this.field(form,"lengthUnit"),originReason:this.field(form,"originReason"),notes:this.field(form,"notes")}});}
            else if(form.matches("[data-stud-composition-requirement]")){event.preventDefault();await this.request("stud-composition-requirement-set",{planId:plan.id,expectedVersion:plan.rowVersion,requirementItemId:this.field(form,"requirementItemId"),sectionId:section.id,disposition:"ASSIGNED"});}
            else if(form.matches("[data-stud-composition-requirement-exclude]")){event.preventDefault();await this.request("stud-composition-requirement-set",{planId:plan.id,expectedVersion:plan.rowVersion,requirementItemId:this.field(form,"requirementItemId"),disposition:"EXCLUDED",reason:this.field(form,"reason")});}
            else if(form.matches("[data-stud-composition-claim]")){event.preventDefault();await this.request("stud-composition-claim-link",{planId:plan.id,expectedVersion:plan.rowVersion,sectionId:section.id,claimId:this.field(form,"claimId"),order:section.claims.length,rationale:"Explicit user placement in Composition."});}
            else if(form.matches("[data-stud-draft-save]")){event.preventDefault();const version=await this.request("stud-draft-save-version",{assignmentId:assignment.id,draftId:this.state.draft.id,expectedVersion:this.state.draft.rowVersion,sections:[{sectionId:section.id,content:this.field(form,"content")}],changeReason:this.field(form,"changeReason")});this.showToast(this.parent.parent.view,`DRAFT VERSION ${version.versionNumber} SAVED`);}
            else return false;
            await this.reload();return true;
        }catch(error){event.preventDefault();this.showToast(this.parent.parent.view,error.message||"COMPOSITION SAVE FAILED");return true;}
    }
}

if(typeof window!=="undefined")window.StudCompositionWorkspace=StudCompositionWorkspace;
if(typeof module!=="undefined")module.exports={StudCompositionWorkspace};
