"use strict";

const Academic = require("./studAcademicModel.class.js");
const Domain = require("./studLecturerCommitteeModel.class.js");

function camel(row){if(!row)return null;const value={};Object.entries(row).forEach(([key,item])=>value[key.replace(/_([a-z])/g,(_m,c)=>c.toUpperCase())]=item);return value;}
function parsed(row,fields={}){const value=camel(row);if(!value)return null;Object.entries(fields).forEach(([key,fallback])=>{value[key]=Domain.parseJson(value[`${key}Json`],fallback);delete value[`${key}Json`];});return value;}
function frozen(rows,mapper=camel){return Object.freeze(rows.map(row=>Object.freeze(mapper(row))));}

class StudLecturerCommitteeRepository{
    constructor(store){if(!store)throw new Error("StudAcademicStore is required.");this.store=store;store.initialize();this.db=store.db;}
    transaction(work){return this.store.transaction(work);}
    sessionRow(id){const value=parsed(this.db.prepare("SELECT * FROM stud_lecturer_review_sessions WHERE id=?").get(Academic.safeId(id,"Review Session ID")),{committee:[],citationSnapshot:{},runIds:[]});if(!value)throw new Academic.StudError("NOT_FOUND","Lecturer Review Session does not exist.");return Object.freeze(value);}
    passRow(id){const value=camel(this.db.prepare("SELECT * FROM stud_lecturer_reviewer_passes WHERE id=?").get(Academic.safeId(id,"Reviewer Pass ID")));if(!value)throw new Academic.StudError("NOT_FOUND","Reviewer Pass does not exist.");return Object.freeze(value);}
    findingRow(id){const value=camel(this.db.prepare("SELECT * FROM stud_lecturer_review_findings WHERE id=?").get(Academic.safeId(id,"Review Finding ID")));if(!value)throw new Academic.StudError("NOT_FOUND","Review Finding does not exist.");return Object.freeze(value);}
    planRow(id){const value=camel(this.db.prepare("SELECT * FROM stud_correction_plans WHERE id=?").get(Academic.safeId(id,"Correction Plan ID")));if(!value)throw new Academic.StudError("NOT_FOUND","Correction Plan does not exist.");return Object.freeze(value);}
    itemRow(id){const value=camel(this.db.prepare("SELECT * FROM stud_correction_items WHERE id=?").get(Academic.safeId(id,"Correction Item ID")));if(!value)throw new Academic.StudError("NOT_FOUND","Correction Item does not exist.");return Object.freeze(value);}
    correctionRow(id){const value=parsed(this.db.prepare("SELECT * FROM stud_correction_sessions WHERE id=?").get(Academic.safeId(id,"Correction Session ID")),{selectedItemIds:[],protectedOverrides:[]});if(!value)throw new Academic.StudError("NOT_FOUND","Correction Session does not exist.");return Object.freeze(value);}
    passes(sessionId){return frozen(this.db.prepare("SELECT * FROM stud_lecturer_reviewer_passes WHERE session_id=? ORDER BY CASE provenance WHEN 'DETERMINISTIC' THEN 0 ELSE 1 END,reviewer_role,id").all(sessionId));}
    findings(sessionId,options={}){const limit=Math.max(1,Math.min(Number(options.limit)||200,Domain.LIMITS.findings));let sql="SELECT * FROM stud_lecturer_review_findings WHERE session_id=?",args=[sessionId];if(options.status){sql+=" AND status=?";args.push(options.status);}if(options.severity){sql+=" AND severity=?";args.push(options.severity);}sql+=" ORDER BY CASE severity WHEN 'BLOCKING' THEN 0 WHEN 'MAJOR' THEN 1 WHEN 'MINOR' THEN 2 ELSE 3 END,updated_at DESC,id DESC LIMIT ?";args.push(limit);return frozen(this.db.prepare(sql).all(...args));}
    findingEvents(id){return frozen(this.db.prepare("SELECT * FROM stud_lecturer_finding_events WHERE finding_id=? ORDER BY created_at,id LIMIT 200").all(id));}
    synthesis(sessionId){return frozen(this.db.prepare(`SELECT s.*,GROUP_CONCAT(l.finding_id) finding_ids FROM stud_lecturer_synthesis s LEFT JOIN stud_lecturer_synthesis_findings l ON l.synthesis_id=s.id WHERE s.session_id=? GROUP BY s.id ORDER BY CASE s.synthesis_kind WHEN 'DISAGREEMENT' THEN 0 WHEN 'AGREEMENT' THEN 1 WHEN 'COMPLEMENTARY' THEN 2 ELSE 3 END,s.id`).all(sessionId).map(row=>({...row,finding_ids:row.finding_ids?row.finding_ids.split(","):[]})),row=>{const value=camel(row);value.findingIds=value.findingIds||[];return value;});}
    estimates(sessionId){return frozen(this.db.prepare("SELECT * FROM stud_lecturer_formative_estimates WHERE session_id=? ORDER BY created_at DESC,id DESC LIMIT 20").all(sessionId),row=>parsed(row,{rubricSnapshot:[],reasoning:[]}));}
    hydrateSession(id){const value=this.sessionRow(id);return Object.freeze({...value,passes:this.passes(value.id),findings:this.findings(value.id),synthesis:this.synthesis(value.id),formativeEstimates:this.estimates(value.id)});}
    listSessions(assignmentId,limit=25){return frozen(this.db.prepare("SELECT * FROM stud_lecturer_review_sessions WHERE assignment_id=? ORDER BY updated_at DESC,id DESC LIMIT ?").all(assignmentId,Math.max(1,Math.min(Number(limit)||25,100))),row=>parsed(row,{committee:[],citationSnapshot:{},runIds:[]}));}
    insertSession(value){const id=Academic.createId("lecturer_review"),now=Academic.now();this.db.prepare(`INSERT INTO stud_lecturer_review_sessions (id,assignment_id,draft_id,source_draft_version_id,source_content_hash,composition_plan_id,composition_plan_revision,composition_plan_hash,requirements_contract_id,requirements_contract_revision,requirements_contract_hash,research_plan_id,research_plan_revision,research_plan_hash,source_humanisation_session_id,source_humanisation_profile_revision_id,committee_json,citation_snapshot_json,citation_snapshot_hash,state,run_ids_json,row_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'CREATED','[]',1,?,?)`).run(id,value.assignmentId,value.draftId,value.sourceDraftVersionId,value.sourceContentHash,value.compositionPlanId,value.compositionPlanRevision,value.compositionPlanHash,value.requirementsContractId,value.requirementsContractRevision,value.requirementsContractHash,value.researchPlanId,value.researchPlanRevision,value.researchPlanHash,value.sourceHumanisationSessionId,value.sourceHumanisationProfileRevisionId,JSON.stringify(value.committee),JSON.stringify(value.citationSnapshot),value.citationSnapshotHash,now,now);const statement=this.db.prepare(`INSERT INTO stud_lecturer_reviewer_passes (id,session_id,assignment_id,reviewer_role,applicability,focus,state,provenance,row_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'LOCAL_MODEL',1,?,?)`);value.committee.forEach(member=>statement.run(Academic.createId("lecturer_pass"),id,value.assignmentId,member.role,member.applicability,member.focus,member.applicability==="APPLICABLE"?"PENDING":"NOT_APPLICABLE",now,now));return this.hydrateSession(id);}
    insertDeterministicPass(session){const existing=this.db.prepare("SELECT id FROM stud_lecturer_reviewer_passes WHERE session_id=? AND reviewer_role='REQUIREMENTS' AND provenance='DETERMINISTIC'").get(session.id);if(existing)return this.passRow(existing.id);const id=Academic.createId("lecturer_pass"),now=Academic.now();this.db.prepare(`INSERT INTO stud_lecturer_reviewer_passes (id,session_id,assignment_id,reviewer_role,applicability,focus,state,provenance,row_version,created_at,updated_at,finished_at) VALUES (?,?,?,'REQUIREMENTS','APPLICABLE','Deterministic integrity and coverage checks','COMPLETE','DETERMINISTIC',1,?,?,?)`).run(id,session.id,session.assignmentId,now,now,now);return this.passRow(id);}
    setSession(session,value){const now=Academic.now(),result=this.db.prepare(`UPDATE stud_lecturer_review_sessions SET state=?,runtime=?,model=?,capability_state=?,run_ids_json=?,error_summary=?,row_version=row_version+1,updated_at=?,finished_at=? WHERE id=? AND row_version=?`).run(value.state,value.runtime??session.runtime,value.model??session.model,value.capabilityState??session.capabilityState,JSON.stringify(value.runIds??session.runIds),value.errorSummary??null,now,["COMPLETE","PARTIAL","FAILED","CANCELLED"].includes(value.state)?now:null,session.id,session.rowVersion);if(!result.changes)throw new Academic.StudError("STALE_REVIEW_SESSION","Review Session changed before it could be saved.");return this.hydrateSession(session.id);}
    setPass(pass,value){const now=Academic.now(),result=this.db.prepare(`UPDATE stud_lecturer_reviewer_passes SET state=?,runtime=?,model=?,capability_state=?,run_id=?,error_summary=?,row_version=row_version+1,updated_at=?,finished_at=? WHERE id=? AND row_version=?`).run(value.state,value.runtime??pass.runtime,value.model??pass.model,value.capabilityState??pass.capabilityState,value.runId??pass.runId,value.errorSummary??null,now,["COMPLETE","FAILED","CANCELLED","NOT_APPLICABLE"].includes(value.state)?now:null,pass.id,pass.rowVersion);if(!result.changes)throw new Academic.StudError("STALE_REVIEW_PASS","Reviewer Pass changed before it could be saved.");return this.passRow(pass.id);}
    insertFinding(session,pass,value,provenance){const id=Academic.createId("lecturer_finding"),now=Academic.now(),fingerprint=Domain.semanticFingerprint(value);this.db.prepare(`INSERT INTO stud_lecturer_review_findings (id,session_id,pass_id,assignment_id,reviewer_role,provenance,category,severity,status,title,explanation,basis_type,basis_id,requirement_item_id,claim_id,evidence_id,citation_paper_id,draft_section_id,excerpt,locator,recommended_action,rationale,semantic_fingerprint,row_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?, 'OPEN',?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,?,?)`).run(id,session.id,pass.id,session.assignmentId,pass.reviewerRole,provenance,value.category,value.severity,value.title,value.explanation,value.basisType,value.basisId,value.requirementItemId,value.claimId,value.evidenceId,value.citationPaperId,value.draftSectionId,value.excerpt,value.locator,value.recommendedAction,value.rationale,fingerprint,now,now);this.db.prepare("INSERT INTO stud_lecturer_finding_events (id,finding_id,from_status,to_status,actor,note,created_at) VALUES (?,?,NULL,'OPEN','SYSTEM',NULL,?)").run(Academic.createId("finding_event"),id,now);return this.findingRow(id);}
    updateFinding(finding,status,note){const now=Academic.now(),result=this.db.prepare("UPDATE stud_lecturer_review_findings SET status=?,row_version=row_version+1,updated_at=? WHERE id=? AND row_version=?").run(status,now,finding.id,finding.rowVersion);if(!result.changes)throw new Academic.StudError("STALE_REVIEW_FINDING","Review Finding changed before it could be updated.");this.db.prepare("INSERT INTO stud_lecturer_finding_events (id,finding_id,from_status,to_status,actor,note,created_at) VALUES (?,?,?,?, 'USER',?,?)").run(Academic.createId("finding_event"),finding.id,finding.status,status,note||null,now);return Object.freeze({...this.findingRow(finding.id),history:this.findingEvents(finding.id)});}
    clearSynthesis(sessionId){this.db.prepare("DELETE FROM stud_lecturer_synthesis WHERE session_id=?").run(sessionId);}
    insertSynthesis(session,value,findingIds){const id=Academic.createId("lecturer_synthesis"),now=Academic.now();this.db.prepare("INSERT INTO stud_lecturer_synthesis (id,session_id,assignment_id,synthesis_kind,title,summary,cluster_fingerprint,created_at) VALUES (?,?,?,?,?,?,?,?)").run(id,session.id,session.assignmentId,value.kind,value.title,value.summary,Domain.hash([...findingIds].sort()),now);const link=this.db.prepare("INSERT INTO stud_lecturer_synthesis_findings (synthesis_id,finding_id) VALUES (?,?)");findingIds.forEach(findingId=>link.run(id,findingId));return id;}
    insertEstimate(session,value){const id=Academic.createId("formative_estimate"),now=Academic.now();this.db.prepare(`INSERT INTO stud_lecturer_formative_estimates (id,session_id,assignment_id,state,rubric_snapshot_json,rubric_snapshot_hash,range_low,range_high,readiness_label,reasoning_json,runtime,model,capability_state,run_id,error_summary,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,session.id,session.assignmentId,value.state,JSON.stringify(value.rubricSnapshot),value.rubricSnapshotHash,value.rangeLow,value.rangeHigh,value.readinessLabel,JSON.stringify(value.reasoning),value.runtime,value.model,value.capabilityState,value.runId,value.errorSummary,now);return Object.freeze(parsed(this.db.prepare("SELECT * FROM stud_lecturer_formative_estimates WHERE id=?").get(id),{rubricSnapshot:[],reasoning:[]}));}
    insertPlan(session,value,findings){const id=Academic.createId("correction_plan"),now=Academic.now();this.db.prepare("INSERT INTO stud_correction_plans (id,assignment_id,review_session_id,source_draft_version_id,title,state,row_version,created_at,updated_at) VALUES (?,?,?,?,?,'ACTIVE',1,?,?)").run(id,session.assignmentId,session.id,session.sourceDraftVersionId,value.title,now,now);const itemStatement=this.db.prepare("INSERT INTO stud_correction_items (id,plan_id,assignment_id,title,action_type,state,instructions,section_id,item_order,row_version,created_at,updated_at) VALUES (?,?,?,?,?,'PENDING',?,?,?,1,?,?)"),link=this.db.prepare("INSERT INTO stud_correction_item_findings (correction_item_id,finding_id) VALUES (?,?)");findings.forEach((entry,index)=>{const itemId=Academic.createId("correction_item");itemStatement.run(itemId,id,session.assignmentId,entry.title,entry.actionType,entry.instructions,entry.sectionId,index,now,now);entry.findingIds.forEach(findingId=>link.run(itemId,findingId));});return this.hydratePlan(id);}
    planItems(planId){return frozen(this.db.prepare(`SELECT i.*,GROUP_CONCAT(l.finding_id) finding_ids FROM stud_correction_items i LEFT JOIN stud_correction_item_findings l ON l.correction_item_id=i.id WHERE i.plan_id=? GROUP BY i.id ORDER BY i.item_order,i.id`).all(planId),row=>{const value=camel(row);value.findingIds=value.findingIds?value.findingIds.split(","):[];return value;});}
    hydratePlan(id){const plan=this.planRow(id);return Object.freeze({...plan,items:this.planItems(plan.id),sessions:this.listCorrections(plan.assignmentId,plan.id,25)});}
    listPlans(assignmentId,limit=25){return frozen(this.db.prepare("SELECT * FROM stud_correction_plans WHERE assignment_id=? ORDER BY updated_at DESC,id DESC LIMIT ?").all(assignmentId,Math.max(1,Math.min(Number(limit)||25,100))));}
    updateItem(item,value){const now=Academic.now(),result=this.db.prepare("UPDATE stud_correction_items SET action_type=?,state=?,instructions=?,row_version=row_version+1,updated_at=? WHERE id=? AND row_version=?").run(value.actionType,value.state,value.instructions,now,item.id,item.rowVersion);if(!result.changes)throw new Academic.StudError("STALE_CORRECTION_ITEM","Correction Item changed before it could be updated.");return this.itemRow(item.id);}
    insertCorrection(plan,value,sections){const id=Academic.createId("correction_session"),now=Academic.now();this.db.prepare(`INSERT INTO stud_correction_sessions (id,assignment_id,correction_plan_id,source_draft_version_id,source_content_hash,state,selected_item_ids_json,protected_overrides_json,integrity_state,row_version,created_at,updated_at) VALUES (?,?,?,?,?,'CREATED',?,?,'PENDING',1,?,?)`).run(id,plan.assignmentId,plan.id,plan.sourceDraftVersionId,value.sourceContentHash,JSON.stringify(value.selectedItemIds),JSON.stringify(value.protectedOverrides),now,now);const statement=this.db.prepare("INSERT INTO stud_correction_session_sections (id,session_id,section_id,section_order,source_content_hash,protected_spans_json,integrity_state,decision,created_at,updated_at) VALUES (?,?,?,?,?,?,'PENDING','PENDING',?,?)");sections.forEach(item=>statement.run(Academic.createId("correction_section"),id,item.sectionId,item.sectionOrder,item.sourceContentHash,JSON.stringify(item.protectedSpans),now,now));return this.hydrateCorrection(id);}
    correctionSections(id){return frozen(this.db.prepare("SELECT * FROM stud_correction_session_sections WHERE session_id=? ORDER BY section_order,id").all(id),row=>parsed(row,{protectedSpans:[]}));}
    correctionChecks(id){return frozen(this.db.prepare("SELECT * FROM stud_correction_integrity_checks WHERE session_id=? ORDER BY section_id,check_type,id").all(id),row=>parsed(row,{sourceValues:[],candidateValues:[]}));}
    hydrateCorrection(id){const value=this.correctionRow(id);return Object.freeze({...value,sections:this.correctionSections(id),integrityChecks:this.correctionChecks(id)});}
    listCorrections(assignmentId,planId=null,limit=25){let sql="SELECT * FROM stud_correction_sessions WHERE assignment_id=?",args=[assignmentId];if(planId){sql+=" AND correction_plan_id=?";args.push(planId);}sql+=" ORDER BY updated_at DESC,id DESC LIMIT ?";args.push(Math.max(1,Math.min(Number(limit)||25,100)));return frozen(this.db.prepare(sql).all(...args),row=>parsed(row,{selectedItemIds:[],protectedOverrides:[]}));}
    setCorrection(session,value){const now=Academic.now(),result=this.db.prepare(`UPDATE stud_correction_sessions SET state=?,runtime=?,model=?,capability_state=?,run_id=?,candidate_hash=?,integrity_state=?,decision=?,resulting_draft_version_id=?,error_summary=?,row_version=row_version+1,updated_at=?,finished_at=? WHERE id=? AND row_version=?`).run(value.state,value.runtime??session.runtime,value.model??session.model,value.capabilityState??session.capabilityState,value.runId??session.runId,value.candidateHash??session.candidateHash,value.integrityState??session.integrityState,value.decision??session.decision,value.resultingDraftVersionId??session.resultingDraftVersionId,value.errorSummary??null,now,["ACCEPTED","REJECTED","FAILED","CANCELLED"].includes(value.state)?now:null,session.id,session.rowVersion);if(!result.changes)throw new Academic.StudError("STALE_CORRECTION_SESSION","Correction Session changed before it could be saved.");return this.hydrateCorrection(session.id);}
    saveCorrectionCandidate(session,sections,checks,value){const now=Academic.now();this.db.prepare("DELETE FROM stud_correction_integrity_checks WHERE session_id=?").run(session.id);const update=this.db.prepare("UPDATE stud_correction_session_sections SET candidate_content=?,candidate_content_hash=?,integrity_state=?,updated_at=? WHERE session_id=? AND section_id=?");sections.forEach(item=>update.run(item.candidateContent,item.candidateContentHash,item.integrityState,now,session.id,item.sectionId));const insert=this.db.prepare("INSERT INTO stud_correction_integrity_checks (id,session_id,section_id,check_type,state,override_authorized,source_values_json,candidate_values_json,summary,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)");checks.forEach(item=>insert.run(Academic.createId("correction_check"),session.id,item.sectionId||null,item.type,item.state,item.overrideAuthorized?1:0,JSON.stringify(item.sourceValues||[]),JSON.stringify(item.candidateValues||[]),item.summary,now));return this.setCorrection(session,value);}
    decideCorrection(session,value){const now=Academic.now(),result=this.db.prepare("UPDATE stud_correction_sessions SET state=?,decision=?,resulting_draft_version_id=?,row_version=row_version+1,updated_at=?,finished_at=? WHERE id=? AND row_version=? AND state IN ('CANDIDATE_READY','NEEDS_REVIEW')").run(value.state,value.decision,value.resultingDraftVersionId||null,now,now,session.id,session.rowVersion);if(!result.changes)throw new Academic.StudError("STALE_CORRECTION_SESSION","Correction Session changed before the decision was saved.");const statement=this.db.prepare("UPDATE stud_correction_session_sections SET decision=?,updated_at=? WHERE session_id=? AND section_id=?");value.sectionDecisions.forEach(item=>statement.run(item.decision,now,session.id,item.sectionId));return this.hydrateCorrection(session.id);}
}

module.exports=Object.freeze({StudLecturerCommitteeRepository,camel,parsed});
