"use strict";

const Academic = require("./studAcademicModel.class.js");
const Citations = require("./studCitationService.class.js");
const Domain = require("./studClaimEvidenceModel.class.js");
const {StudClaimEvidenceRepository} = require("./studClaimEvidenceRepository.class.js");

const DIRECT_TYPES = Object.freeze(["ACADEMIC_DOCUMENT", "RESEARCH_PAPER", "RESOURCE", "NOTE", "DATASET", "NOTEBOOK", "COMPUTE_RESULT", "REVISION_ITEM", "REPOSITORY_REFERENCE"]);

class StudClaimEvidenceService {
    constructor(options = {}) {
        if (!options.store) throw new Error("StudAcademicStore is required.");
        this.store = options.store;
        this.repository = options.repository || new StudClaimEvidenceRepository(this.store);
        this.workingContext = options.workingContextService || null;
        this.artifacts = options.artifactOperationsService || null;
        this.researchPlans = options.researchPlanService || null;
    }

    assignment(id) { const value=this.store.getEntity("ASSIGNMENT",Academic.safeId(id,"Assignment ID")); if(!value)throw new Academic.StudError("NOT_FOUND","Assignment does not exist."); return value; }
    limit(value, fallback, maximum) { const result=value===undefined?fallback:Number(value); if(!Number.isInteger(result)||result<1||result>maximum)throw new Academic.StudError("INVALID_INPUT",`Limit must be between 1 and ${maximum}.`); return result; }
    scopedClaim(assignmentId, claimId) { const claim=this.repository.claim(claimId); if(claim.assignmentId!==Academic.safeId(assignmentId,"Assignment ID"))throw new Academic.StudError("CROSS_ASSIGNMENT_CLAIM","Claim does not belong to this Assignment."); return claim; }
    scopedEvidence(assignmentId, evidenceId) { const evidence=this.repository.evidence(evidenceId); if(evidence.assignmentId!==Academic.safeId(assignmentId,"Assignment ID"))throw new Academic.StudError("CROSS_ASSIGNMENT_EVIDENCE","Evidence does not belong to this Assignment."); return evidence; }

    contextScope(assignment, planId, topicId, questionId, workflowNodeId) {
        let plan=null,topic=null,question=null,node=null;
        if(planId){plan=this.repository.db.prepare("SELECT id,assignment_id,lifecycle FROM stud_research_plans WHERE id=?").get(Academic.safeId(planId,"Research Plan ID"));if(!plan||plan.assignment_id!==assignment.id)throw new Academic.StudError("CROSS_PLAN_CLAIM","Research Plan does not belong to this Assignment.");}
        if(topicId){if(!plan)throw new Academic.StudError("INVALID_INPUT","Research Topic requires a Research Plan.");topic=this.repository.db.prepare("SELECT id,plan_id,assignment_id FROM stud_research_topics WHERE id=?").get(Academic.safeId(topicId,"Research Topic ID"));if(!topic||topic.plan_id!==plan.id||topic.assignment_id!==assignment.id)throw new Academic.StudError("CROSS_PLAN_CLAIM","Research Topic does not belong to this Plan.");}
        if(questionId){if(!topic)throw new Academic.StudError("INVALID_INPUT","Research Question requires a Topic.");question=this.repository.db.prepare("SELECT id,topic_id,plan_id,assignment_id FROM stud_research_questions WHERE id=?").get(Academic.safeId(questionId,"Research Question ID"));if(!question||question.topic_id!==topic.id||question.plan_id!==plan.id||question.assignment_id!==assignment.id)throw new Academic.StudError("CROSS_PLAN_CLAIM","Research Question does not belong to this Topic.");}
        if(workflowNodeId){node=this.repository.db.prepare("SELECT n.id,w.assignment_id FROM stud_workflow_nodes n JOIN stud_workflow_instances w ON w.id=n.workflow_id WHERE n.id=?").get(Academic.safeId(workflowNodeId,"Workflow node ID"));if(!node||node.assignment_id!==assignment.id)throw new Academic.StudError("INVALID_INPUT","Workflow node does not belong to this Assignment.");}
        return {planId:plan&&plan.id||null,topicId:topic&&topic.id||null,researchQuestionId:question&&question.id||null,workflowNodeId:node&&node.id||null};
    }

    requirementLinks(assignmentId, ids) {
        return Domain.normalizeIds(ids,"Requirement Item ID",Domain.LIMITS.requirementLinks).map(id=>{
            const row=this.repository.db.prepare(`SELECT i.id,i.item_hash,c.assignment_id FROM stud_requirement_items i JOIN stud_requirement_contracts c ON c.id=i.contract_id WHERE i.id=?`).get(id);
            if(!row||row.assignment_id!==assignmentId)throw new Academic.StudError("INVALID_REQUIREMENT_LINK","Requirement Item does not belong to this Assignment.");
            return {id:row.id,snapshotHash:row.item_hash||Domain.canonicalHash({id:row.id})};
        });
    }

    semanticParent(assignmentId, parentClaimId, planId, childId = null) {
        if(!parentClaimId)return null;
        const parent=this.scopedClaim(assignmentId,parentClaimId);
        if(childId&&parent.id===childId)throw new Academic.StudError("CLAIM_HIERARCHY_CYCLE","A Claim cannot be its own parent.");
        if(planId&&parent.planId&&parent.planId!==planId)throw new Academic.StudError("CROSS_PLAN_CLAIM","Parent Claim belongs to a different Research Plan.");
        let cursor=parent,depth=0;
        while(cursor&&cursor.parentSemanticClaimId){if(cursor.parentSemanticClaimId===childId)throw new Academic.StudError("CLAIM_HIERARCHY_CYCLE","Claim hierarchy cannot contain a cycle.");cursor=this.repository.claim(cursor.parentSemanticClaimId);if(cursor.assignmentId!==assignmentId)throw new Academic.StudError("CROSS_ASSIGNMENT_CLAIM","Claim hierarchy cannot cross Assignments.");depth+=1;if(depth>8)throw new Academic.StudError("CLAIM_HIERARCHY_DEPTH","Claim hierarchy exceeds its bounded depth.");}
        return parent.id;
    }

    createClaim(input = {}) {
        Academic.assertAllowedKeys(input,["assignmentId","claim","origin"],"Claim creation");
        const assignment=this.assignment(input.assignmentId), value=Domain.normalizeClaim(input.claim||{});
        const scope=this.contextScope(assignment,value.planId,value.topicId,value.researchQuestionId,value.workflowNodeId);
        const links=this.requirementLinks(assignment.id,value.requirementItemIds),parentSemanticClaimId=this.semanticParent(assignment.id,value.parentClaimId,scope.planId);
        return this.repository.transaction(()=>{const claim=this.repository.insertClaim({claimKey:Academic.createId("claim_lineage"),assignmentId:assignment.id,...scope,text:value.text,type:value.type,origin:Academic.enumValue(input.origin||"USER",Domain.CLAIM_ORIGINS,"Claim origin","USER"),revision:1,parentClaimId:null,parentSemanticClaimId,rationale:value.rationale,userNotes:value.userNotes});this.repository.replaceRequirements(claim.id,links);return this.repository.hydrateClaim(claim.id);});
    }

    updateClaim(input = {}) {
        Academic.assertAllowedKeys(input,["assignmentId","claimId","expectedVersion","claim"],"Claim update");
        const assignment=this.assignment(input.assignmentId), current=this.scopedClaim(assignment.id,input.claimId);
        if(current.lifecycle!=="DRAFT")throw new Academic.StudError("REVIEWED_CLAIM_IMMUTABLE","Reviewed Claim content cannot be edited in place. Create a new revision.");
        this.repository.assertVersion(current,input.expectedVersion,"STALE_CLAIM_VERSION");
        const existingLinks=this.repository.requirementLinks(current.id).map(item=>item.requirementItemId), value=Domain.normalizeClaim(input.claim||{},{...current,requirementItemIds:existingLinks});
        const scope=this.contextScope(assignment,value.planId,value.topicId,value.researchQuestionId,value.workflowNodeId), links=this.requirementLinks(assignment.id,value.requirementItemIds),parentSemanticClaimId=this.semanticParent(assignment.id,value.parentClaimId,scope.planId,current.id);
        return this.repository.transaction(()=>{const updated=this.repository.updateDraftClaim({id:current.id,expectedVersion:current.rowVersion,...scope,parentSemanticClaimId,text:value.text,type:value.type,rationale:value.rationale,userNotes:value.userNotes});this.repository.replaceRequirements(current.id,links);return this.repository.hydrateClaim(updated.id);});
    }

    reviewClaim(input = {}) {
        Academic.assertAllowedKeys(input,["assignmentId","claimId","expectedVersion"],"Claim review");
        const claim=this.scopedClaim(input.assignmentId,input.claimId); if(claim.lifecycle!=="DRAFT")throw new Academic.StudError("INVALID_CLAIM_TRANSITION","Only a Draft Claim can be reviewed.");
        this.repository.assertVersion(claim,input.expectedVersion,"STALE_CLAIM_VERSION");
        const hydrated=this.repository.hydrateClaim(claim.id),hash=Domain.canonicalHash({assignmentId:claim.assignmentId,planId:claim.planId,topicId:claim.topicId,researchQuestionId:claim.researchQuestionId,workflowNodeId:claim.workflowNodeId,parentSemanticClaimId:claim.parentSemanticClaimId,text:claim.claimText,type:claim.claimType,rationale:claim.rationale,requirements:hydrated.requirements.map(item=>({id:item.requirementItemId,hash:item.requirementSnapshotHash}))});
        return this.repository.transaction(()=>this.repository.reviewClaim(claim.id,claim.rowVersion,hash));
    }

    createClaimRevision(input = {}) {
        Academic.assertAllowedKeys(input,["assignmentId","claimId","expectedVersion"],"Claim revision");
        const source=this.scopedClaim(input.assignmentId,input.claimId); if(source.lifecycle!=="REVIEWED")throw new Academic.StudError("INVALID_CLAIM_TRANSITION","A new Claim revision requires the current reviewed Claim.");
        this.repository.assertVersion(source,input.expectedVersion,"STALE_CLAIM_VERSION");
        const pointer=this.repository.db.prepare("SELECT current_reviewed_claim_id,current_draft_claim_id FROM stud_claim_pointers WHERE claim_key=?").get(source.claimKey);
        if(!pointer||pointer.current_reviewed_claim_id!==source.id)throw new Academic.StudError("INVALID_CLAIM_TRANSITION","Only the current reviewed Claim can start a revision.");
        if(pointer.current_draft_claim_id)throw new Academic.StudError("DRAFT_EXISTS","This Claim already has a Draft revision.");
        const requirements=this.repository.requirementLinks(source.id).map(item=>({id:item.requirementItemId,snapshotHash:item.requirementSnapshotHash}));
        return this.repository.transaction(()=>{const draft=this.repository.insertClaim({claimKey:source.claimKey,assignmentId:source.assignmentId,planId:source.planId,topicId:source.topicId,researchQuestionId:source.researchQuestionId,workflowNodeId:source.workflowNodeId,text:source.claimText,type:source.claimType,origin:"USER",revision:source.revision+1,parentClaimId:source.id,parentSemanticClaimId:source.parentSemanticClaimId,rationale:source.rationale,userNotes:source.userNotes});this.repository.replaceRequirements(draft.id,requirements);return this.repository.hydrateClaim(draft.id);});
    }

    claims(input = {}) { Academic.assertAllowedKeys(input,["assignmentId","planId","topicId","lifecycle","beforeUpdatedAt","limit"],"Claim query"); const assignment=this.assignment(input.assignmentId);return this.repository.listClaims({assignmentId:assignment.id,planId:input.planId||null,topicId:input.topicId||null,lifecycle:input.lifecycle?Academic.enumValue(input.lifecycle,Domain.CLAIM_LIFECYCLES,"Claim lifecycle"):null,beforeUpdatedAt:input.beforeUpdatedAt?Academic.optionalDate(input.beforeUpdatedAt,"Claim cursor"):null,limit:this.limit(input.limit,50,Domain.LIMITS.page)}); }
    claim(input = {}) { Academic.assertAllowedKeys(input,["assignmentId","claimId"],"Claim read");const claim=this.scopedClaim(input.assignmentId,input.claimId);return Object.freeze({...this.repository.hydrateClaim(claim.id),history:this.repository.claimHistory(claim.claimKey),links:this.repository.linksForClaim(claim.id)}); }

    scopeCanonical(assignment, type, id) {
        const object=this.store.getEntity(type,Academic.safeId(id,"Source object ID")); if(!object)throw new Academic.StudError("SOURCE_MISSING","Canonical source does not exist.");
        if(!this.workingContext||!this.workingContext.relationshipScope(type,object,assignment.courseId||null,assignment.id))throw new Academic.StudError("CONTEXT_RELATION_REQUIRED","Evidence source must already belong to this Assignment or its Course.");
        return Object.freeze({...object,entityType:type});
    }

    exactSource(assignment, input) {
        const type=Academic.enumValue(input.sourceObjectType,Domain.SOURCE_OBJECT_TYPES,"Evidence source type");
        const locator=input.locator&&typeof input.locator==="object"&&!Array.isArray(input.locator)?input.locator:{};
        let object=null,artifactId=null,documentId=null,extractionId=null,chunkId=null,pageStart=null,pageEnd=null,citationPaperId=input.citationPaperId?Academic.safeId(input.citationPaperId,"Citation paper ID"):null,locationType=input.locationType?Academic.enumValue(input.locationType,Domain.EVIDENCE_LOCATION_TYPES,"Evidence location type"):null,snapshot=null,excerpt=Academic.optionalText(input.excerpt,"Evidence excerpt",Domain.LIMITS.excerpt),method=Academic.optionalText(input.extractionMethod,"Extraction method",240);
        if(type==="ARTIFACT"){
            if(!this.artifacts)throw new Academic.StudError("UNAVAILABLE","Artifact service is unavailable.");
            const artifact=this.artifacts.scopedArtifact(assignment.id,input.sourceObjectId);artifactId=artifact.id;locationType||="ARTIFACT_VERSION";snapshot={type,id:artifact.id,canonicalObjectType:artifact.canonicalObjectType,canonicalObjectId:artifact.canonicalObjectId,rowVersion:artifact.rowVersion,integrityHash:artifact.integrityHash,availability:artifact.availabilityState};
            return {sourceObjectType:type,sourceObjectId:artifact.id,artifactId,citationPaperId,locationType,documentId,extractionId,chunkId,pageStart,pageEnd,locatorJson:Domain.boundedJson(locator,"Evidence locator"),excerpt,sourceSnapshotHash:Domain.canonicalHash(snapshot),extractionMethod:method||"EXPLICIT_ARTIFACT_REFERENCE"};
        }
        if(!DIRECT_TYPES.includes(type))throw new Academic.StudError("INVALID_INPUT","Unsupported canonical Evidence source type.");
        object=this.scopeCanonical(assignment,type,input.sourceObjectId);
        if(type==="ACADEMIC_DOCUMENT"){
            documentId=object.id;
            if(locator.chunkId){const chunk=this.repository.db.prepare(`SELECT c.*,x.document_id,x.status extraction_status,x.created_at extraction_created_at FROM stud_document_chunks c JOIN stud_document_extractions x ON x.id=c.extraction_id WHERE c.id=?`).get(Academic.safeId(locator.chunkId,"Document chunk ID"));if(!chunk||chunk.document_id!==object.id)throw new Academic.StudError("INVALID_PROVENANCE","Document chunk does not belong to this source.");extractionId=chunk.extraction_id;chunkId=chunk.id;pageStart=chunk.page_start;pageEnd=chunk.page_end;locationType="DOCUMENT_CHUNK";excerpt ||= String(chunk.content||"").slice(0,Domain.LIMITS.excerpt);snapshot={type,id:object.id,documentChecksum:object.checksum,extractionId,extractionStatus:chunk.extraction_status,chunkId,contentHash:chunk.content_hash,pageStart,pageEnd};}
            else if(locator.extractionId&&locator.pageStart){const extraction=this.repository.db.prepare("SELECT * FROM stud_document_extractions WHERE id=? AND document_id=?").get(Academic.safeId(locator.extractionId,"Extraction ID"),object.id);if(!extraction)throw new Academic.StudError("INVALID_PROVENANCE","Extraction does not belong to this document.");extractionId=extraction.id;pageStart=Academic.optionalNonNegativeInteger(locator.pageStart,"Page start",100000);pageEnd=locator.pageEnd?Academic.optionalNonNegativeInteger(locator.pageEnd,"Page end",100000):pageStart;if(pageStart<1||pageEnd<pageStart)throw new Academic.StudError("INVALID_PROVENANCE","Document page range is invalid.");locationType="DOCUMENT_PAGE";const pages=this.repository.db.prepare("SELECT page_number,text_hash,text_content FROM stud_document_pages WHERE extraction_id=? AND page_number BETWEEN ? AND ? ORDER BY page_number").all(extractionId,pageStart,pageEnd);if(!pages.length)throw new Academic.StudError(extraction.status==="OCR_REQUIRED"?"OCR_BLOCKED":"INVALID_PROVENANCE","The selected document pages are not inspectable.");snapshot={type,id:object.id,documentChecksum:object.checksum,extractionId,status:extraction.status,pages:pages.map(page=>({page:page.page_number,hash:page.text_hash}))};excerpt ||= pages.map(page=>page.text_content||"").join("\n").slice(0,Domain.LIMITS.excerpt);}
            else throw new Academic.StudError("EXACT_PROVENANCE_REQUIRED","Document Evidence requires an exact chunk or extraction/page reference.");
            if(!citationPaperId&&object.sourcePaperId)citationPaperId=object.sourcePaperId;
        } else if(type==="RESEARCH_PAPER"){
            locationType||="SOURCE_RECORD";citationPaperId ||= object.id;snapshot={type,id:object.id,title:object.title,year:object.year,doi:object.doi||null,sourceUrl:object.sourceUrl||null,updatedAt:object.updatedAt};
        } else if(type==="DATASET"){
            locationType||="DATASET_RANGE";if(!Object.keys(locator).length)throw new Academic.StudError("EXACT_PROVENANCE_REQUIRED","Dataset Evidence requires a field, range or query locator.");snapshot={type,id:object.id,checksum:object.checksum||null,rowCount:object.rowCount||null,columnsJson:object.columnsJson||null,locator};
        } else if(type==="NOTEBOOK"){
            locationType||="NOTEBOOK_CELL";const cellId=Academic.safeId(locator.cellId,"Notebook cell ID"),cell=this.repository.db.prepare("SELECT * FROM stud_notebook_cells WHERE id=? AND notebook_id=?").get(cellId,object.id);if(!cell)throw new Academic.StudError("INVALID_PROVENANCE","Notebook cell does not belong to this Notebook.");let output=null;if(locator.outputId){output=this.repository.db.prepare("SELECT * FROM stud_notebook_outputs WHERE id=? AND cell_id=?").get(Academic.safeId(locator.outputId,"Notebook output ID"),cell.id);if(!output)throw new Academic.StudError("INVALID_PROVENANCE","Notebook output does not belong to this cell.");}snapshot={type,id:object.id,cellId:cell.id,cellUpdatedAt:cell.updated_at,cellSourceHash:Domain.canonicalHash(cell.source),outputId:output&&output.id||null,outputHash:output?Domain.canonicalHash({text:output.text_content,artifact:output.artifact_reference,metadata:output.metadata_json}):null};
        } else if(type==="COMPUTE_RESULT"){
            locationType||="COMPUTE_RESULT";snapshot={type,id:object.id,operation:object.operation,input:object.normalizedInputJson||object.inputJson,output:object.outputJson,units:object.unitsJson,updatedAt:object.updatedAt};
        } else {
            locationType||="SOURCE_RECORD";snapshot={type,id:object.id,updatedAt:object.updatedAt,checksum:object.checksum||null,title:object.title||object.prompt||null};
        }
        if(citationPaperId){const paper=this.store.getEntity("RESEARCH_PAPER",citationPaperId);if(!paper)throw new Academic.StudError("CITATION_SOURCE_MISMATCH","Citation paper does not exist.");if(type==="RESEARCH_PAPER"&&paper.id!==object.id)throw new Academic.StudError("CITATION_SOURCE_MISMATCH","Citation metadata refers to a different Research Paper.");if(type==="ACADEMIC_DOCUMENT"&&object.sourcePaperId&&paper.id!==object.sourcePaperId)throw new Academic.StudError("CITATION_SOURCE_MISMATCH","Citation metadata does not match the Document's canonical source Paper.");}
        return {sourceObjectType:type,sourceObjectId:object.id,artifactId,citationPaperId,locationType,documentId,extractionId,chunkId,pageStart,pageEnd,locatorJson:Domain.boundedJson(locator,"Evidence locator"),excerpt,sourceSnapshotHash:Domain.canonicalHash(snapshot),extractionMethod:method||"EXPLICIT_USER_SELECTION"};
    }

    dossierSource(assignment, dossierItemId) {
        const id=Academic.safeId(dossierItemId,"Dossier Item ID"),item=this.repository.db.prepare("SELECT * FROM stud_topic_dossier_items WHERE id=?").get(id);if(!item||item.assignment_id!==assignment.id)throw new Academic.StudError("INVALID_INPUT","Dossier Item does not belong to this Assignment.");if(item.disposition!=="ACCEPTED")throw new Academic.StudError("DOSSIER_NOT_ACCEPTED","Only explicitly accepted Dossier material can be promoted to Evidence.");
        if(item.artifact_id)return {dossierItemId:id,planId:item.plan_id,topicId:item.topic_id,sourceObjectType:"ARTIFACT",sourceObjectId:item.artifact_id};
        return {dossierItemId:id,planId:item.plan_id,topicId:item.topic_id,sourceObjectType:item.canonical_object_type,sourceObjectId:item.canonical_object_id};
    }

    createEvidence(input = {}) {
        Academic.assertAllowedKeys(input,["assignmentId","planId","topicId","dossierItemId","sourceObjectType","sourceObjectId","locationType","locator","excerpt","citationPaperId","reviewerNote","extractionMethod","origin"],"Evidence creation");
        const assignment=this.assignment(input.assignmentId), promoted=input.dossierItemId?this.dossierSource(assignment,input.dossierItemId):null;
        const planId=promoted&&promoted.planId||input.planId||null,topicId=promoted&&promoted.topicId||input.topicId||null;this.contextScope(assignment,planId,topicId,null,null);
        const exact=this.exactSource(assignment,{...input,sourceObjectType:promoted&&promoted.sourceObjectType||input.sourceObjectType,sourceObjectId:promoted&&promoted.sourceObjectId||input.sourceObjectId});
        const reviewerNote=Academic.optionalText(input.reviewerNote,"Evidence review note",Domain.LIMITS.note);
        return this.repository.insertEvidence({assignmentId:assignment.id,planId,topicId,dossierItemId:promoted&&promoted.dossierItemId||null,...exact,reviewerNote,origin:Academic.enumValue(input.origin||"USER",Domain.EVIDENCE_ORIGINS,"Evidence origin","USER")});
    }

    validateCitationIdentity(evidence, citationPaperId) {
        if(!citationPaperId)return null;
        const citationId=Academic.safeId(citationPaperId,"Citation paper ID"),paper=this.store.getEntity("RESEARCH_PAPER",citationId);
        if(!paper)throw new Academic.StudError("CITATION_SOURCE_MISMATCH","Citation paper does not exist.");
        if(evidence.sourceObjectType==="RESEARCH_PAPER"&&evidence.sourceObjectId!==paper.id)throw new Academic.StudError("CITATION_SOURCE_MISMATCH","Citation metadata refers to a different Research Paper.");
        if(evidence.sourceObjectType==="ACADEMIC_DOCUMENT"){
            const document=this.store.getEntity("ACADEMIC_DOCUMENT",evidence.sourceObjectId);
            if(document&&document.sourcePaperId&&document.sourcePaperId!==paper.id)throw new Academic.StudError("CITATION_SOURCE_MISMATCH","Citation metadata does not match the Document's canonical source Paper.");
        }
        return paper.id;
    }

    updateEvidence(input = {}) { Academic.assertAllowedKeys(input,["assignmentId","evidenceId","expectedVersion","citationPaperId","locator","excerpt","reviewerNote"],"Evidence update");const evidence=this.scopedEvidence(input.assignmentId,input.evidenceId);if(evidence.reviewState!=="UNREVIEWED")throw new Academic.StudError("REVIEWED_EVIDENCE_IMMUTABLE","Reviewed Evidence cannot be edited in place.");this.repository.assertVersion(evidence,input.expectedVersion,"STALE_EVIDENCE_VERSION");let citation=evidence.citationPaperId;if(input.citationPaperId!==undefined)citation=input.citationPaperId?this.validateCitationIdentity(evidence,input.citationPaperId):null;return this.repository.updateEvidence({id:evidence.id,expectedVersion:evidence.rowVersion,citationPaperId:citation,locatorJson:input.locator===undefined?evidence.locatorJson:Domain.boundedJson(input.locator,"Evidence locator"),excerpt:input.excerpt===undefined?evidence.excerpt:Academic.optionalText(input.excerpt,"Evidence excerpt",Domain.LIMITS.excerpt),reviewerNote:input.reviewerNote===undefined?evidence.reviewerNote:Academic.optionalText(input.reviewerNote,"Evidence review note",Domain.LIMITS.note)}); }
    reviewEvidence(input = {}) { Academic.assertAllowedKeys(input,["assignmentId","evidenceId","expectedVersion"],"Evidence review");const evidence=this.scopedEvidence(input.assignmentId,input.evidenceId);if(evidence.reviewState!=="UNREVIEWED")throw new Academic.StudError("INVALID_EVIDENCE_TRANSITION","Only unreviewed Evidence can be reviewed.");this.repository.assertVersion(evidence,input.expectedVersion,"STALE_EVIDENCE_VERSION");const hash=Domain.canonicalHash({assignmentId:evidence.assignmentId,sourceObjectType:evidence.sourceObjectType,sourceObjectId:evidence.sourceObjectId,locationType:evidence.locationType,documentId:evidence.documentId,extractionId:evidence.extractionId,chunkId:evidence.chunkId,pageStart:evidence.pageStart,pageEnd:evidence.pageEnd,locator:evidence.locator,excerpt:evidence.excerpt,sourceSnapshotHash:evidence.sourceSnapshotHash,citationPaperId:evidence.citationPaperId});return this.repository.reviewEvidence(evidence.id,evidence.rowVersion,hash); }
    evidence(input = {}) { Academic.assertAllowedKeys(input,["assignmentId","evidenceId"],"Evidence read");return this.withIntegrity(this.scopedEvidence(input.assignmentId,input.evidenceId)); }
    evidenceList(input = {}) { Academic.assertAllowedKeys(input,["assignmentId","planId","topicId","reviewState","beforeUpdatedAt","limit"],"Evidence query");const assignment=this.assignment(input.assignmentId);return Object.freeze(this.repository.listEvidence({assignmentId:assignment.id,planId:input.planId||null,topicId:input.topicId||null,reviewState:input.reviewState?Academic.enumValue(input.reviewState,Domain.EVIDENCE_REVIEW_STATES,"Evidence review state"):null,beforeUpdatedAt:input.beforeUpdatedAt?Academic.optionalDate(input.beforeUpdatedAt,"Evidence cursor"):null,limit:this.limit(input.limit,50,Domain.LIMITS.page)}).map(item=>this.withIntegrity(item))); }

    currentSnapshot(evidence) {
        try {
            if(evidence.sourceObjectType==="ARTIFACT"){const artifact=this.artifacts&&this.artifacts.scopedArtifact(evidence.assignmentId,evidence.sourceObjectId);if(!artifact)return {state:"SOURCE_MISSING"};return {state:artifact.availabilityState==="MISSING"?"SOURCE_MISSING":"CURRENT",hash:Domain.canonicalHash({type:"ARTIFACT",id:artifact.id,canonicalObjectType:artifact.canonicalObjectType,canonicalObjectId:artifact.canonicalObjectId,rowVersion:artifact.rowVersion,integrityHash:artifact.integrityHash,availability:artifact.availabilityState})};}
            const object=this.store.getEntity(evidence.sourceObjectType,evidence.sourceObjectId);if(!object)return {state:"SOURCE_MISSING"};
            if(evidence.locationType==="DOCUMENT_CHUNK"){const chunk=this.repository.db.prepare(`SELECT c.*,x.document_id,x.status extraction_status FROM stud_document_chunks c JOIN stud_document_extractions x ON x.id=c.extraction_id WHERE c.id=?`).get(evidence.chunkId);if(!chunk||chunk.document_id!==evidence.documentId)return {state:"SOURCE_MISSING"};const latest=this.repository.db.prepare("SELECT id,status FROM stud_document_extractions WHERE document_id=? ORDER BY created_at DESC LIMIT 1").get(evidence.documentId);if(latest&&latest.status==="OCR_REQUIRED")return {state:"OCR_BLOCKED"};const hash=Domain.canonicalHash({type:"ACADEMIC_DOCUMENT",id:object.id,documentChecksum:object.checksum,extractionId:chunk.extraction_id,extractionStatus:chunk.extraction_status,chunkId:chunk.id,contentHash:chunk.content_hash,pageStart:chunk.page_start,pageEnd:chunk.page_end});return {state:hash===evidence.sourceSnapshotHash&&(!latest||latest.id===chunk.extraction_id)?"CURRENT":"SOURCE_CHANGED",hash};}
            if(evidence.locationType==="DOCUMENT_PAGE"){const extraction=this.repository.db.prepare("SELECT * FROM stud_document_extractions WHERE id=? AND document_id=?").get(evidence.extractionId,evidence.documentId);if(!extraction)return {state:"SOURCE_MISSING"};const latest=this.repository.db.prepare("SELECT id,status FROM stud_document_extractions WHERE document_id=? ORDER BY created_at DESC LIMIT 1").get(evidence.documentId);if((latest&&latest.status==="OCR_REQUIRED")||extraction.status==="OCR_REQUIRED")return {state:"OCR_BLOCKED"};const pages=this.repository.db.prepare("SELECT page_number,text_hash FROM stud_document_pages WHERE extraction_id=? AND page_number BETWEEN ? AND ? ORDER BY page_number").all(extraction.id,evidence.pageStart,evidence.pageEnd);if(!pages.length)return {state:"SOURCE_MISSING"};const hash=Domain.canonicalHash({type:"ACADEMIC_DOCUMENT",id:object.id,documentChecksum:object.checksum,extractionId:extraction.id,status:extraction.status,pages:pages.map(page=>({page:page.page_number,hash:page.text_hash}))});return {state:hash===evidence.sourceSnapshotHash&&(!latest||latest.id===extraction.id)?"CURRENT":"SOURCE_CHANGED",hash};}
            if(evidence.sourceObjectType==="RESEARCH_PAPER"){const hash=Domain.canonicalHash({type:"RESEARCH_PAPER",id:object.id,title:object.title,year:object.year,doi:object.doi||null,sourceUrl:object.sourceUrl||null,updatedAt:object.updatedAt});return {state:hash===evidence.sourceSnapshotHash?"CURRENT":"SOURCE_CHANGED",hash};}
            if(evidence.sourceObjectType==="DATASET"){const hash=Domain.canonicalHash({type:"DATASET",id:object.id,checksum:object.checksum||null,rowCount:object.rowCount||null,columnsJson:object.columnsJson||null,locator:evidence.locator||{}});return {state:hash===evidence.sourceSnapshotHash?"CURRENT":"SOURCE_CHANGED",hash};}
            if(evidence.sourceObjectType==="COMPUTE_RESULT"){const hash=Domain.canonicalHash({type:"COMPUTE_RESULT",id:object.id,operation:object.operation,input:object.normalizedInputJson||object.inputJson,output:object.outputJson,units:object.unitsJson,updatedAt:object.updatedAt});return {state:hash===evidence.sourceSnapshotHash?"CURRENT":"SOURCE_CHANGED",hash};}
            if(evidence.sourceObjectType==="NOTEBOOK"){const locator=evidence.locator||{},cell=this.repository.db.prepare("SELECT * FROM stud_notebook_cells WHERE id=? AND notebook_id=?").get(locator.cellId,object.id);if(!cell)return {state:"SOURCE_MISSING"};let output=null;if(locator.outputId){output=this.repository.db.prepare("SELECT * FROM stud_notebook_outputs WHERE id=? AND cell_id=?").get(locator.outputId,cell.id);if(!output)return {state:"SOURCE_MISSING"};}const hash=Domain.canonicalHash({type:"NOTEBOOK",id:object.id,cellId:cell.id,cellUpdatedAt:cell.updated_at,cellSourceHash:Domain.canonicalHash(cell.source),outputId:output&&output.id||null,outputHash:output?Domain.canonicalHash({text:output.text_content,artifact:output.artifact_reference,metadata:output.metadata_json}):null});return {state:hash===evidence.sourceSnapshotHash?"CURRENT":"SOURCE_CHANGED",hash};}
            const hash=Domain.canonicalHash({type:evidence.sourceObjectType,id:object.id,updatedAt:object.updatedAt,checksum:object.checksum||null,title:object.title||object.prompt||null});return {state:hash===evidence.sourceSnapshotHash?"CURRENT":"SOURCE_CHANGED",hash};
        } catch(error){if(error.code==="NOT_FOUND"||error.code==="SOURCE_MISSING")return {state:"SOURCE_MISSING"};throw error;}
    }

    citationIntegrity(evidence, freshness) {
        if(freshness.state==="SOURCE_MISSING")return {state:"SOURCE_UNAVAILABLE",rendered:null,reason:"The canonical source is unavailable."};
        if(freshness.state==="SOURCE_CHANGED")return {state:"SOURCE_CHANGED",rendered:null,reason:"The source changed after this Evidence snapshot was recorded."};
        if(["DOCUMENT_CHUNK","DOCUMENT_PAGE"].includes(evidence.locationType)&&!evidence.chunkId&&!evidence.pageStart)return {state:"PROVENANCE_MISSING",rendered:null,reason:"Exact document provenance is unavailable."};
        if(!evidence.citationPaperId)return {state:"MISSING",rendered:null,reason:"No canonical bibliographic record is linked."};
        const paper=this.store.getEntity("RESEARCH_PAPER",evidence.citationPaperId);if(!paper)return {state:"SOURCE_MISMATCH",rendered:null,reason:"Linked bibliographic metadata no longer resolves."};
        if(evidence.sourceObjectType==="RESEARCH_PAPER"&&paper.id!==evidence.sourceObjectId)return {state:"SOURCE_MISMATCH",rendered:null,reason:"Bibliographic metadata refers to a different canonical source."};
        if(evidence.sourceObjectType==="ACADEMIC_DOCUMENT"){const document=this.store.getEntity("ACADEMIC_DOCUMENT",evidence.sourceObjectId);if(document&&document.sourcePaperId&&document.sourcePaperId!==paper.id)return {state:"SOURCE_MISMATCH",rendered:null,reason:"Bibliographic metadata refers to a different canonical source than this Document."};}
        if(!paper.title)return {state:"METADATA_INCOMPLETE",rendered:null,reason:"Bibliographic metadata has no title."};
        try {const rendered=Citations.render([paper],"harvard1");return {state:"READY",rendered,reason:"Citation.js rendered the linked canonical bibliographic record."};} catch(error){return {state:"RENDER_FAILED",rendered:null,reason:String(error.message||"Citation rendering failed.").slice(0,500)};}
    }

    withIntegrity(evidence) { const freshness=this.currentSnapshot(evidence),citation=this.citationIntegrity(evidence,freshness);return Object.freeze({...evidence,freshness:Object.freeze(freshness),citationIntegrity:Object.freeze(citation)}); }

    linkEvidence(input = {}) { Academic.assertAllowedKeys(input,["assignmentId","claimId","evidenceId","relationshipType","rationale","origin"],"Claim-Evidence assessment");const claim=this.scopedClaim(input.assignmentId,input.claimId),evidence=this.scopedEvidence(input.assignmentId,input.evidenceId);if(claim.assignmentId!==evidence.assignmentId)throw new Academic.StudError("CROSS_ASSIGNMENT_EVIDENCE","Claim and Evidence must belong to the same Assignment.");if(claim.planId&&evidence.planId&&claim.planId!==evidence.planId)throw new Academic.StudError("CROSS_PLAN_EVIDENCE","Claim and Evidence belong to different Research Plans.");const existing=this.repository.db.prepare("SELECT revision FROM stud_claim_evidence_links WHERE claim_id=? AND evidence_id=? ORDER BY revision DESC LIMIT 1").get(claim.id,evidence.id);if(existing)throw new Academic.StudError("LINK_EXISTS","A Claim-Evidence assessment already exists; revise it instead.");return this.repository.insertLink({assignmentId:claim.assignmentId,claimId:claim.id,evidenceId:evidence.id,relationshipType:Academic.enumValue(input.relationshipType||"NOT_ASSESSED",Domain.EVIDENCE_RELATIONSHIPS,"Evidence relationship","NOT_ASSESSED"),revision:1,parentLinkId:null,rationale:Academic.optionalText(input.rationale,"Relationship rationale",Domain.LIMITS.rationale),origin:Academic.enumValue(input.origin||"USER",Domain.EVIDENCE_ORIGINS,"Relationship origin","USER")}); }
    updateLink(input = {}) { Academic.assertAllowedKeys(input,["assignmentId","linkId","expectedVersion","relationshipType","rationale"],"Claim-Evidence assessment update");const link=this.repository.link(input.linkId);if(link.assignmentId!==Academic.safeId(input.assignmentId,"Assignment ID"))throw new Academic.StudError("CROSS_ASSIGNMENT_EVIDENCE","Claim-Evidence assessment belongs to another Assignment.");if(link.lifecycle!=="DRAFT")throw new Academic.StudError("REVIEWED_RELATIONSHIP_IMMUTABLE","Reviewed Claim-Evidence assessment cannot be edited in place.");this.repository.assertVersion(link,input.expectedVersion,"STALE_CLAIM_EVIDENCE_VERSION");return this.repository.updateLink({id:link.id,expectedVersion:link.rowVersion,relationshipType:input.relationshipType===undefined?link.relationshipType:Academic.enumValue(input.relationshipType,Domain.EVIDENCE_RELATIONSHIPS,"Evidence relationship"),rationale:input.rationale===undefined?link.rationale:Academic.optionalText(input.rationale,"Relationship rationale",Domain.LIMITS.rationale)}); }
    reviewLink(input = {}) { Academic.assertAllowedKeys(input,["assignmentId","linkId","expectedVersion"],"Claim-Evidence assessment review");const link=this.repository.link(input.linkId);if(link.assignmentId!==Academic.safeId(input.assignmentId,"Assignment ID"))throw new Academic.StudError("CROSS_ASSIGNMENT_EVIDENCE","Claim-Evidence assessment belongs to another Assignment.");if(link.lifecycle!=="DRAFT")throw new Academic.StudError("INVALID_CLAIM_EVIDENCE_TRANSITION","Only a Draft assessment can be reviewed.");if(link.relationshipType==="NOT_ASSESSED")throw new Academic.StudError("UNRESOLVED_RELATIONSHIP","Assess how the Evidence relates to the Claim before review.");this.repository.assertVersion(link,input.expectedVersion,"STALE_CLAIM_EVIDENCE_VERSION");return this.repository.reviewLink(link.id,link.rowVersion); }
    reviseLink(input = {}) { Academic.assertAllowedKeys(input,["assignmentId","linkId","expectedVersion"],"Claim-Evidence assessment revision");const source=this.repository.link(input.linkId);if(source.assignmentId!==Academic.safeId(input.assignmentId,"Assignment ID"))throw new Academic.StudError("CROSS_ASSIGNMENT_EVIDENCE","Claim-Evidence assessment belongs to another Assignment.");if(source.lifecycle!=="REVIEWED")throw new Academic.StudError("INVALID_CLAIM_EVIDENCE_TRANSITION","A new assessment revision requires reviewed state.");this.repository.assertVersion(source,input.expectedVersion,"STALE_CLAIM_EVIDENCE_VERSION");const draft=this.repository.db.prepare("SELECT id FROM stud_claim_evidence_links WHERE claim_id=? AND evidence_id=? AND lifecycle='DRAFT'").get(source.claimId,source.evidenceId);if(draft)throw new Academic.StudError("DRAFT_EXISTS","This assessment already has a Draft revision.");return this.repository.insertLink({assignmentId:source.assignmentId,claimId:source.claimId,evidenceId:source.evidenceId,relationshipType:source.relationshipType,revision:source.revision+1,parentLinkId:source.id,rationale:source.rationale,origin:"USER"}); }

    map(input = {}) {
        Academic.assertAllowedKeys(input,["assignmentId","planId","topicId","claimLimit","evidenceLimit"],"Evidence Map");const assignment=this.assignment(input.assignmentId),claims=this.repository.listClaims({assignmentId:assignment.id,planId:input.planId||null,topicId:input.topicId||null,lifecycle:null,beforeUpdatedAt:null,limit:this.limit(input.claimLimit,Domain.LIMITS.mapClaims,Domain.LIMITS.mapClaims)}),claimIds=new Set(claims.map(item=>item.id));
        const links=this.repository.linksForAssignment(assignment.id,this.limit(input.evidenceLimit,Domain.LIMITS.mapEvidence,Domain.LIMITS.mapEvidence)).filter(link=>claimIds.has(link.claimId));const evidenceIds=[...new Set(links.map(link=>link.evidenceId))],evidence=new Map(evidenceIds.map(id=>{const value=this.withIntegrity(this.repository.evidence(id));return [id,value];}));
        const nodes=claims.map(claim=>{const claimLinks=links.filter(link=>link.claimId===claim.id),reviewed=claimLinks.filter(link=>link.lifecycle==="REVIEWED"),counts=reviewed.reduce((result,link)=>{result[link.relationshipType]=(result[link.relationshipType]||0)+1;return result;},{}),issues=[];if(!reviewed.length)issues.push("NO_REVIEWED_EVIDENCE");reviewed.forEach(link=>{const item=evidence.get(link.evidenceId);if(item.freshness.state!=="CURRENT")issues.push(item.freshness.state);if(item.citationIntegrity.state!=="READY")issues.push(`CITATION_${item.citationIntegrity.state}`);});return Object.freeze({claim,links:Object.freeze(claimLinks.map(link=>Object.freeze({...link,evidence:evidence.get(link.evidenceId)}))),summary:Object.freeze({reviewedEvidence:reviewed.length,supporting:counts.SUPPORTS||0,contradicting:counts.CONTRADICTS||0,qualifying:counts.QUALIFIES||0,contextualising:counts.CONTEXTUALISES||0,unassessed:claimLinks.filter(link=>link.relationshipType==="NOT_ASSESSED").length,issues:Object.freeze([...new Set(issues)])})});});
        const unassessed=this.repository.listEvidence({assignmentId:assignment.id,planId:input.planId||null,topicId:input.topicId||null,reviewState:null,beforeUpdatedAt:null,limit:Domain.LIMITS.mapEvidence}).filter(item=>!links.some(link=>link.evidenceId===item.id)).map(item=>this.withIntegrity(item));
        return Object.freeze({assignment,claims:Object.freeze(nodes),unassessedEvidence:Object.freeze(unassessed),truncated:Object.freeze({claims:claims.length>=Domain.LIMITS.mapClaims,evidence:links.length>=Domain.LIMITS.mapEvidence}),explanation:"Counts describe explicit reviewed records only. They are not a quality score or completion percentage."});
    }

    sourcePreview(input = {}) { Academic.assertAllowedKeys(input,["assignmentId","evidenceId"],"Evidence source preview");const evidence=this.withIntegrity(this.scopedEvidence(input.assignmentId,input.evidenceId));let preview={kind:evidence.sourceObjectType,sourceId:evidence.sourceObjectId,locationType:evidence.locationType,locator:evidence.locator,excerpt:evidence.excerpt,pageStart:evidence.pageStart,pageEnd:evidence.pageEnd};if(evidence.sourceObjectType==="ACADEMIC_DOCUMENT"&&evidence.documentId)preview={...preview,document:this.store.getEntity("ACADEMIC_DOCUMENT",evidence.documentId),chunk:evidence.chunkId?this.repository.db.prepare("SELECT id,page_start,page_end,content,content_hash,provenance_json FROM stud_document_chunks WHERE id=?").get(evidence.chunkId):null};else if(evidence.sourceObjectType==="ARTIFACT"&&this.artifacts)preview={...preview,artifact:this.artifacts.scopedArtifact(evidence.assignmentId,evidence.sourceObjectId)};else preview={...preview,source:this.store.getEntity(evidence.sourceObjectType,evidence.sourceObjectId)};return Object.freeze({evidence,preview:Object.freeze(preview)}); }
}

module.exports = Object.freeze({StudClaimEvidenceService});
